import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid^="row-"]')
console.log('stage', await page.locator('[data-testid="stage-now"]').textContent())
console.log('advance?', await page.locator('[data-testid="stage-advance"]').count())
console.log('wars', await page.locator('[data-testid="war-picker"] option').allTextContents())
console.log('viewing', await page.locator('[data-testid="lw-viewing"]').textContent())
console.log('bidwin', await page.locator('[data-testid="bid-window"]').textContent().catch(()=>null))
console.log('figtoggle', await page.locator('[data-testid="figures-toggle"]').getAttribute('aria-expanded').catch(()=>null))
const rows = await page.$$eval('[data-testid^="row-"]', els => els.map(e => e.getAttribute('data-testid')))
console.log('rows', rows.length, rows.slice(0,40).join(' '))
const me = await page.evaluate(() => { const r = [...document.querySelectorAll('[data-testid^="row-"]')].find(e => /ranger/i.test(e.textContent)); return r && r.getAttribute('data-testid') })
console.log('ranger row', me)
const heads = await page.$$eval('[data-testid^="head-"]', els => els.slice(0,3).map(e=>e.getAttribute('data-testid')))
console.log('heads', heads)
console.log('scrollLeft', await page.evaluate(()=>document.querySelector('.mx-wrap').scrollLeft))
await snap(page, 'p1-member-full')
await browser.close()
