import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('ad')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="stage-advance"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-slash-2026-02-02"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="decide-approve"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="stage-advance"]').click(); await page.waitForTimeout(500)
console.log('admin stage', await page.locator('[data-testid="stage-now"]').innerText())
await page.locator('button:has-text("Logout")').first().click(); await page.waitForTimeout(600)
await page.fill('#luser','us'); await page.fill('#lpass','us'); await page.click('#loginForm button[type=submit]')
await page.waitForSelector('#vWeek .day', { state: 'attached' }); await page.waitForTimeout(500)
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
console.log('member stage', await page.locator('[data-testid="stage-now"]').innerText(), 'advance', await page.locator('[data-testid="stage-advance"]').count(), 'viewing', await page.locator('[data-testid="lw-viewing"]').innerText())
if ((await page.locator('[data-testid="counts-toggle"]').getAttribute('aria-expanded'))==='true') await page.locator('[data-testid="counts-toggle"]').click()
if ((await page.locator('[data-testid="figures-toggle"]').getAttribute('aria-expanded'))==='true') await page.locator('[data-testid="figures-toggle"]').click()
await page.waitForTimeout(500)
console.log('blade 2feb', await page.locator('[data-testid="cell-slash-2026-02-02"] .c').getAttribute('class').catch(()=>null))
await page.locator('[data-testid="cell-bane-2026-01-14"]').click(); await page.waitForTimeout(400)
const sheets = await page.$$eval('[data-testid$="-sheet"], [data-testid="bid-picker"], [data-testid="daylist"]', els => els.map(e=>e.getAttribute('data-testid')))
console.log('member tap own row sheets', sheets)
await page.locator('[data-testid="cell-slash-2026-02-02"]').click(); await page.waitForTimeout(400)
console.log('member tap blade approved', await page.$$eval('[data-testid$="-sheet"], [data-testid="bid-picker"], [data-testid="daylist"]', els => els.map(e=>e.getAttribute('data-testid')+': '+e.innerText.replace(/\n/g,' | '))))
await snap(page, 'p10-member-published')
await browser.close()
