import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
console.log('person-bane', await page.locator('[data-testid="person-bane"]').textContent())
console.log('counts-toggle', await box(page,'[data-testid="counts-toggle"]'), await page.locator('[data-testid="counts-toggle"]').textContent(), await page.locator('[data-testid="counts-toggle"]').getAttribute('aria-expanded'))
console.log('figures-toggle', await box(page,'[data-testid="figures-toggle"]'))
// fold manning + put drawer away
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
for (const d of ['2026-01-14','2026-01-15','2026-01-16','2026-02-11']) console.log(d, await box(page, `[data-testid="cell-bane-${d}"]`), await page.locator(`[data-testid="cell-bane-${d}"]`).textContent())
console.log('row-bane', await box(page,'[data-testid="row-bane"]'))
await snap(page, 'p2-folded')
// other-person row tap
await page.locator('[data-testid="cell-dice-2026-01-14"]').click(); await page.waitForTimeout(300)
console.log('picker on other row', await page.locator('[data-testid="bid-picker"]').count())
await page.locator('[data-testid="cell-bane-2026-01-14"]').click()
await page.locator('[data-testid="bid-picker"]').waitFor()
console.log('picker', await box(page,'[data-testid="bid-picker"]'))
console.log('picker text', (await page.locator('[data-testid="bid-picker"]').innerText()).replace(/\n/g,' | '))
for (const s of ['span-one','span-range','portion-full','portion-am','portion-pm','bid-LL','bid-OL','bid-cancel','decide-approve','decide-shift','bid-clear']) console.log(s, await box(page,`[data-testid="${s}"]`))
await snap(page, 'p2-picker')
await page.locator('[data-testid="bid-LL"]').click(); await page.waitForTimeout(500)
console.log('after', await page.locator('[data-testid="cell-bane-2026-01-14"]').innerText(), await page.locator('[data-testid="cell-bane-2026-01-14"] .c').getAttribute('class'))
console.log('picker after', await page.locator('[data-testid="bid-picker"]').count())
await snap(page, 'p2-after')
// Tap own bid again: what opens
await page.locator('[data-testid="cell-bane-2026-01-14"]').click(); await page.waitForTimeout(400)
console.log('reopen text', (await page.locator('[data-testid="bid-picker"]').innerText().catch(()=> 'none')).replace(/\n/g,' | '))
await snap(page, 'p2-reopen')
await browser.close()
