import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-bane-2026-01-14"]').click()
await page.locator('[data-testid="bid-picker"]').waitFor()
await page.locator('[data-testid="bid-LL"]').click(); await page.waitForTimeout(800)
console.log('picker after', await page.locator('[data-testid="bid-picker"]').count())
console.log('picker text', (await page.locator('[data-testid="bid-picker"]').innerText().catch(()=> 'none')).replace(/\n/g,' | '))
console.log('cell html', await page.locator('[data-testid="cell-bane-2026-01-14"]').innerHTML())
await snap(page, 'p3-after')
await browser.close()
