import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-bane-2026-01-14"]').click()
await page.locator('[data-testid="bid-picker"]').waitFor()
await page.locator('[data-testid="bid-LL"]').click(); await page.waitForTimeout(300)
console.log('note', await box(page,'[data-testid="span-note"]'))
await page.locator('[data-testid="bid-LL"]').click(); await page.waitForTimeout(800)
console.log('picker after 2nd', await page.locator('[data-testid="bid-picker"]').count())
const c = page.locator('[data-testid="cell-bane-2026-01-14"] .c')
console.log('chip', await c.count(), await c.first().innerText().catch(()=>''), await c.first().getAttribute('class').catch(()=>''), await box(page,'[data-testid="cell-bane-2026-01-14"] .c'))
console.log('bal col', await page.locator('[data-testid="bal-bane"]').innerText().catch(()=>'?'), await box(page,'[data-testid="bal-bane"]'))
await snap(page, 'p4-landed')
// range via drag across 20..23 Jan
const a = await page.locator('[data-testid="cell-bane-2026-01-20"]').boundingBox()
const b = await page.locator('[data-testid="cell-bane-2026-01-23"]').boundingBox()
await page.mouse.move(a.x+a.width/2, a.y+a.height/2); await page.mouse.down()
await page.mouse.move(a.x+a.width/2+8, a.y+a.height/2)
await page.mouse.move(b.x+b.width/2, b.y+b.height/2, { steps: 6 })
await snap(page, 'p4-dragging')
await page.mouse.up(); await page.waitForTimeout(400)
console.log('select-sheet', await box(page,'[data-testid="select-sheet"]'))
console.log('sel text', (await page.locator('[data-testid="select-sheet"]').innerText().catch(()=> 'none')).replace(/\n/g,' | '))
for (const s of ['sel-who','sel-span','sel-LL','sel-cancel','sel-approve']) console.log(s, await box(page,`[data-testid="${s}"]`))
await snap(page, 'p4-selsheet')
await page.locator('[data-testid="sel-LL"]').click(); await page.waitForTimeout(500)
console.log('sel after', (await page.locator('[data-testid="select-sheet"]').innerText().catch(()=> 'closed')).replace(/\n/g,' | '))
if (await page.locator('[data-testid="select-sheet"]').count()) { await page.locator('[data-testid="sel-LL"]').click(); await page.waitForTimeout(600) }
for (const d of ['20','21','22','23']) console.log(d, await page.locator(`[data-testid="cell-bane-2026-01-${d}"]`).innerText())
await snap(page, 'p4-range-landed')
await browser.close()
