import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-bane-2026-01-14"]').click()
await page.locator('[data-testid="bid-picker"]').waitFor()
await page.locator('[data-testid="span-range"]').click(); await page.waitForTimeout(300)
console.log('picker', await box(page,'[data-testid="bid-picker"]'))
console.log('month', await page.locator('[data-testid="span-month"]').textContent(), await box(page,'[data-testid="span-day-2026-01-16"]'))
await page.locator('[data-testid="span-day-2026-01-16"]').click(); await page.waitForTimeout(200)
console.log('span-range text', await page.locator('[data-testid="span-range"]').textContent())
await snap(page, 'p5-range')
await page.locator('[data-testid="bid-OL"]').click(); await page.waitForTimeout(300)
console.log('note', await page.locator('[data-testid="span-note"]').textContent().catch(()=>null))
if (await page.locator('[data-testid="bid-picker"]').count()) await page.locator('[data-testid="bid-OL"]').click()
await page.waitForTimeout(600)
for (const d of ['14','15','16']) console.log(d, await page.locator(`[data-testid="cell-bane-2026-01-${d}"]`).innerText())
await page.locator('[data-testid="cell-bane-2026-01-15"]').click(); await page.waitForTimeout(400)
console.log('reopen', (await page.locator('[data-testid="bid-picker"]').innerText().catch(()=>'none')).replace(/\n/g,' | '))
await snap(page, 'p5-reopen')
await browser.close()
