import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('ad')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
console.log('slash', await page.locator('[data-testid="person-slash"]').innerText())
await page.locator('[data-testid="stage-advance"]').click(); await page.waitForTimeout(500)
console.log('stage', await page.locator('[data-testid="stage-now"]').innerText(), '| adv', await page.locator('[data-testid="stage-advance"]').innerText(), '| back', await page.locator('[data-testid="stage-back"]').innerText(), '| bidwin', await page.locator('[data-testid="bid-window"]').count())
await snap(page, 'p7-closed')
await page.locator('[data-testid="cell-slash-2026-02-02"]').click(); await page.waitForTimeout(400)
const sheets = ['bid-picker','daylist','raptor-sheet','select-sheet']
for (const s of sheets) console.log(s, await box(page, `[data-testid="${s}"]`))
console.log('text', (await page.locator('[data-testid="bid-picker"]').innerText().catch(()=>'none')).replace(/\n/g,' | '))
for (const s of ['decide-ack','decide-approve','decide-refuse','decide-shift','bid-clear','cell-slash-2026-02-02']) console.log(s, await box(page,`[data-testid="${s}"]`))
await snap(page, 'p7-decide')
await page.locator('[data-testid="decide-approve"]').click(); await page.waitForTimeout(500)
console.log('sheet after approve', await page.locator('[data-testid="bid-picker"]').count())
console.log('chip', await page.locator('[data-testid="cell-slash-2026-02-02"] .c').getAttribute('class'))
await snap(page, 'p7-approved')
await browser.close()
