import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('ad')
await go(page, 'leavewar')
await page.waitForSelector('[data-testid="row-bane"]')
await page.locator('[data-testid="counts-toggle"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="figures-toggle"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="stage-advance"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-slash-2026-02-02"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="decide-approve"]').click(); await page.waitForTimeout(500)
await page.locator('[data-testid="cell-slash-2026-02-03"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="decide-refuse"]').click(); await page.waitForTimeout(500)
console.log('3feb', await page.locator('[data-testid="cell-slash-2026-02-03"] .c').getAttribute('class'))
await snap(page, 'p8-refused')
// move 3 Feb -> 5 Feb
await page.locator('[data-testid="cell-slash-2026-02-03"]').click(); await page.waitForTimeout(300)
await page.locator('[data-testid="decide-shift"]').click()
await page.locator('[data-testid="move-banner"]').waitFor()
console.log('banner', await box(page,'[data-testid="move-banner"]'), (await page.locator('[data-testid="move-banner"]').innerText()).replace(/\n/g,' | '))
await page.waitForTimeout(500)
await page.mouse.move(1150, 773)
await page.waitForTimeout(200)
await snap(page, 'p8-moving')
await page.locator('[data-testid="cell-slash-2026-02-05"]').click(); await page.waitForTimeout(500)
console.log('confirm?', await page.locator('[data-testid="move-confirm"]').count())
console.log('3feb after', await page.locator('[data-testid="cell-slash-2026-02-03"] .c').count(), '5feb', await page.locator('[data-testid="cell-slash-2026-02-05"] .c').innerText().catch(()=>null), await page.locator('[data-testid="cell-slash-2026-02-05"] .c').getAttribute('class').catch(()=>null))
await snap(page, 'p8-moved')
await page.locator('[data-testid="cell-slash-2026-02-05"]').click(); await page.waitForTimeout(300)
console.log('moved sheet', (await page.locator('[data-testid="bid-picker"]').innerText().catch(()=>'none')).replace(/\n/g,' | '))
await page.locator('[data-testid="bid-cancel"]').click().catch(()=>{})
await page.waitForTimeout(300)
// publish
await page.locator('[data-testid="stage-advance"]').click(); await page.waitForTimeout(800)
console.log('stage', await page.locator('[data-testid="stage-now"]').innerText(), '| adv', await page.locator('[data-testid="stage-advance"]').innerText(), await page.locator('[data-testid="stage-advance"]').isDisabled(), '| back', await page.locator('[data-testid="stage-back"]').innerText())
// any toast / dialog?
console.log('dialogs', await page.locator('[role="dialog"], .toast, [data-testid*="toast"]').count())
await snap(page, 'p8-published')
await page.locator('[data-testid="cell-slash-2026-02-02"]').click(); await page.waitForTimeout(400)
for (const s of ['bid-picker','daylist','raptor-sheet','remarks-sheet']) console.log(s, await box(page,`[data-testid="${s}"]`))
const anySheet = await page.$$eval('[data-testid$="-sheet"], [data-testid="bid-picker"], [data-testid="daylist"]', els => els.map(e=>e.getAttribute('data-testid')+': '+e.innerText.replace(/\n/g,' | ')))
console.log(anySheet)
await snap(page, 'p8-pub-tap')
await browser.close()
