import { browser, fresh, go, box, snap } from './lib.mjs'
const page = await fresh('us')
await go(page, 'tracker')
await page.waitForSelector('#flowSvg .ball', { timeout: 20000 }); await page.waitForTimeout(500)
const ball = id => page.locator(`#flowSvg .ball[data-id="${id}"]`)
console.log('ball sel', await ball('ST-01').count(), await box(page,'#flowSvg .ball[data-id="ST-01"]'))
const ov = async () => (await page.locator('text=COMPLETE').locator('..').innerText().catch(()=>'')).replace(/\n/g,' ')
const html0 = await ball('ST-01').innerHTML()
await ball('ST-01').click(); await page.waitForTimeout(400)
console.log('pop', await box(page,'#pop'), (await page.locator('#pop').innerText()).replace(/\n/g,' | ').slice(0,300))
const btns = await page.$$eval('#pop .opts button', els => els.map(e => { const r=e.getBoundingClientRect(); return [e.textContent, Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height)] }))
console.log(JSON.stringify(btns))
console.log('popDoneDate', await page.locator('#popDoneDate').inputValue(), await box(page,'#popDoneDate'))
await snap(page, 't2-pop')
await page.locator('#pop .opts button', { hasText: /^DCO$/ }).click(); await page.waitForTimeout(600)
console.log('pop after', await page.locator('#pop').count())
const html1 = await ball('ST-01').innerHTML()
console.log('ball changed', html0 !== html1)
console.log('ball class', await ball('ST-01').getAttribute('class'))
const panel = await page.evaluate(() => { const t = [...document.querySelectorAll('*')].find(e => e.children.length===0 && e.textContent.trim()==='DONE'); return t && t.parentElement.outerHTML.slice(0,300) })
console.log(panel)
await snap(page, 't2-done')
// ST-02 now?
await browser.close()
