// S49 — a named group Event keeps group rights and the latest answer. Saber (admin) files for Ace (P), Basher (W), Cotter (G), Ranger + himself;
// Ranger (a member who did not file it) changes his own answer; Saber answers again; Saber denies Basher in OIL Earn; Anvil is added; issue.
import { closeWins, world, closeAll, toInputs, openNew, openDay, setTimes, pic, T, oilAnswer, sleep, readInputs, observe, switchUser, setPerson, listAll, listSearch, listRow, issue, lwMap, crowdCount, signIn, URL_ } from './aa-A-lib.mjs'
import * as L from './lib.mjs'
const dump = async (page, tag) => { const r = await page.evaluate(() => window.INPUTS.filter(x => /walkS49/.test(x.remarks || '')).map(x => window.PEOPLE[x.person]?.cs + '=' + JSON.stringify(x.oil)).sort()); console.log(tag, r.join(' | ')) }
const w = await world({ who: 'ad', size: 'p' })
const A = w.page
await toInputs(A)
await openNew(A, '2026-07-18')
await A.selectOption('#inpEditType', 'Event')
await A.locator('#inpEditPop ' + T('pp-several')).click(); await sleep(400)
for (const p of ['dj', 'glass', 'spanner', 'bane']) { const b = A.locator(`#inpEditPop [data-pp="${p}"]`).first(); await b.scrollIntoViewIfNeeded(); if ((await b.getAttribute('aria-pressed')) !== 'true') await b.click(); await sleep(150) }
{ const a = A.locator('#inpEditAllday'); if (await a.isChecked()) await a.uncheck() }
await setTimes(A, '09:00', '12:00'); await A.fill('#inpEditRmk', 'walkS49 group')
await A.locator('#inpEditSave').click(); await sleep(700)
console.log('question:', (await A.locator(T('oilconf')).innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 120))
await oilAnswer(A, 'yes')
await dump(A, '1 filed with Yes:')
await closeWins(A)
await setPerson(A, 'all'); await openDay(A, '2026-07-18')
console.log('2 calendar day card (one shared group):', (await A.locator('[data-testid="win-inputsday"]').innerText()).replace(/\s+/g, ' ').slice(0, 220))
await pic(A, 's49-1-day-card')
await closeWins(A)
await listAll(A); await listSearch(A, 'walkS49')
console.log('2 List: rows for the group =', await A.locator('tr[data-iid]').filter({ hasText: 'walkS49' }).count())
// 3. Ranger changes his own answer
await switchUser(A, 'us'); await toInputs(A); await setPerson(A, 'all'); await openDay(A, '2026-07-18')
await A.locator('[data-testid="win-inputsday"] .sd-row').filter({ hasText: 'walkS49' }).locator('.sd-open').first().click(); await sleep(800)
await pic(A, 's49-2-ranger-opens-group')
const mine = A.locator('#inpEditPop [data-testid^="oil-revise"]')
console.log('3 Ranger sees', await mine.count(), '"Change…" buttons and "Take me out":', await A.locator('#inpEditPop').getByRole('button', { name: 'Take me out' }).count())
// his own answer is the one inside the "own" block: find the button inside the block that mentions his name / own answer
const ownBlock = await A.evaluate(() => [...document.querySelectorAll('#inpEditPop [data-testid="oil-revise"]')].map(b => b.parentElement.innerText.replace(/\s+/g, ' ').slice(0, 140)))
console.log('3 blocks around the Change… buttons:', JSON.stringify(ownBlock))
const own = A.locator('#inpEditPop [data-testid="oil-revise-own"]').last()
await own.click({ timeout: 4000 }).catch(e => console.log('own Change failed', String(e).slice(0, 80))); await sleep(700)
console.log('3 question for Ranger:', (await A.locator(T('oilconf')).innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 140))
await pic(A, 's49-3-ranger-own-question')
await A.locator(T('oil-no')).click().catch(() => {}); await A.locator(T('oilconf-save')).click().catch(() => {}); await sleep(700)
await dump(A, '3 after Ranger answered No (his own):')
await closeWins(A)
// 4. Saber (filer) answers again
await switchUser(A, 'ad'); await toInputs(A); await setPerson(A, 'all'); await openDay(A, '2026-07-18')
await A.locator('[data-testid="win-inputsday"] .sd-row').filter({ hasText: 'walkS49' }).locator('.sd-open').first().click(); await sleep(800)
const grp = A.locator('#inpEditPop [data-testid="oil-revise"]').first()
console.log('4 filer sees Change… buttons:', await A.locator('#inpEditPop [data-testid="oil-revise"]').count())
await grp.click().catch(e => console.log('group Change failed', String(e).slice(0, 80))); await sleep(700)
console.log('4 question for the filer:', (await A.locator(T('oilconf')).innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 140))
await A.locator(T('oil-yes')).click().catch(() => {}); await A.locator(T('oilconf-save')).click().catch(() => {}); await sleep(700)
await dump(A, '4 after the filer answered Yes again:')
await closeWins(A)
// 5. denial of Basher on the board (desktop tab), then Anvil added by Saber, answer again, issue
const B = await w.ctx.newPage(); await B.setViewportSize({ width: 1440, height: 900 })
B.on('pageerror', e => w.errs.push('B PAGEERROR ' + e)); B.on('console', m => { if (m.type() === 'error') w.errs.push('B CONSOLE ' + m.text()) })
await B.goto(URL_); await signIn(B, 'ad')
await L.go(B, 'editsched'); await L.board(B, 5); await L.oilMode(B, true); await sleep(600)
const bp = B.locator('#schedBoard .puck[data-person="glass"]').filter({ hasNot: B.locator('xpath=ancestor::*[@id="sbRoster"]') })
const cand = await B.evaluate(() => [...document.querySelectorAll('#schedBoard .puck[data-person="glass"]')].filter(e => !e.closest('#sbRoster')).map((e, i) => i + ' ' + e.className + ' in ' + (e.closest('[data-oilitem]')?.getAttribute('data-oilitem') || '-')))
console.log('5 Basher pucks (outside the roster):', JSON.stringify(cand))
const target = B.locator('#schedBoard [data-oilitem^="i:"] .puck[data-person="glass"], #schedBoard .puck.oilglow[data-person="glass"]').first()
await target.scrollIntoViewIfNeeded(); await target.click(); await sleep(700)
await pic(B, 's49-4-board-denied')
const full = async P => P.evaluate(() => window.INPUTS.filter(x => /walkS49/.test(x.remarks || '')).map(x => window.PEOPLE[x.person]?.cs + '=' + JSON.stringify({ oil: x.oil, ...Object.fromEntries(Object.entries(x).filter(([k]) => /oil|deny|off|x$/i.test(k) && k !== 'oil')) })).sort())
console.log('5 after the scheduler denied Basher:', (await full(B)).join(' | '))
// A (Saber): reload, add Anvil to the group, answer again
await A.reload(); await sleep(1000); if (await A.locator('#luser').count()) await signIn(A, 'ad')
await toInputs(A); await setPerson(A, 'all'); await openDay(A, '2026-07-18')
await A.locator('[data-testid="win-inputsday"] .sd-row').filter({ hasText: 'walkS49' }).locator('.sd-open').first().click(); await sleep(800)
const an = A.locator('#inpEditPop [data-pp="shaft"]').first(); await an.scrollIntoViewIfNeeded(); await an.click(); await sleep(300)
await A.locator('#inpEditSave').click(); await sleep(800)
console.log('6 add Anvil -> question:', (await A.locator(T('oilconf')).innerText().catch(() => '')).replace(/s+/g, ' ').slice(0, 130))
await A.locator(T('oil-yes')).click().catch(() => {}); await A.locator(T('oilconf-save')).click().catch(() => {}); await sleep(800)
console.log('6 after adding Anvil and answering Yes:', (await full(A)).join(' | '))
await closeWins(A)
// issue
await B.reload(); await sleep(1000); if (await B.locator('#luser').count()) await signIn(B, 'ad')
console.log('7 ORIG', JSON.stringify(await issue(B, 5)))
const m = await lwMap(B)
console.log('7 credits: Ace', m['Ace'], '| Basher', m['Basher'], '| Cotter', m['Cotter'], '| Ranger', m['Ranger'], '| Saber', m['Saber'], '| Anvil', m['Anvil'])
await pic(B, 's49-5-credits')
console.log('errs', JSON.stringify(w.errs))
await w.ctx.close().catch(() => {})
await closeAll()
