// S30 — every date-writing door enforces one day (desktop, admin). Month drag-pick, editor calendar, List Add, List pencil, cross-month, bar move.
import { closeWins, world, closeAll, toInputs, openNew, openDay, toMonth, fileInput, setTimes, pic, T, oilAnswer, sleep, readInputs, observe, listAll, listSearch, listRow, pencil, closeRowEdit, PE, PSAVE, undoState } from './aa-A-lib.mjs'
const rows = []
const n = page => page.evaluate(() => window.INPUTS.length)
const note = (id, ph, text) => { console.log(id, ph, text); rows.push({ id, ph, text }) }
async function drag(page, from, to, steps = 10) {
  const a = await page.locator(`#inpCal [data-icday="${from}"]`).boundingBox(); const b = await page.locator(`#inpCal [data-icday="${to}"]`).boundingBox()
  await page.mouse.move(a.x + 8, a.y + 8); await page.mouse.down()
  for (let i = 1; i <= steps; i++) await page.mouse.move(a.x + 8 + (b.x - a.x) * i / steps, a.y + 8 + (b.y - a.y) * i / steps)
  await page.mouse.up(); await sleep(500)
}
const msgs = async page => (await observe(page)).msgs.filter(m => /one day|filed|ALL/i.test(m)).join(' | ')
for (const ph of ['allavail', 'all']) {
  const w = await world({ who: 'ad', size: 'd' })
  const page = w.page
  await toInputs(page)
  // 1) month drag across two dates -> "+ Input"
  await toMonth(page, 2026, 6)
  await drag(page, '2026-07-16', '2026-07-17')
  await pic(page, `s30-${ph}-1-drag-picked`)
  console.log(ph, 'after the drag the editor says:', await page.locator('#inpEditPop').innerText().then(t => t.replace(/s+/g, ' ').slice(0, 60)).catch(() => 'no editor'))
  if (await page.locator('#inpEditPop').isVisible().catch(() => false)) {
    await page.selectOption('#inpEditType', 'Duty'); await page.selectOption('#inpEditPerson', ph)
    const ad = page.locator('#inpEditAllday'); if (await ad.isChecked()) await ad.uncheck()
    await setTimes(page, '09:00', '12:00'); await page.fill('#inpEditRmk', `walkS30 drag ${ph}`)
    const n0 = await n(page)
    await page.locator('#inpEditSave').click(); await sleep(600)
    await pic(page, `s30-${ph}-2-drag-save`)
    note('S30-a month-drag two days', ph, `Save -> saved ${await n(page) - n0} | OIL q ${await page.locator(T('oilconf')).isVisible().catch(() => false)} | messages: ${await msgs(page)} | picker line: ${await page.locator(T('pp-why')).first().innerText().catch(() => null)}`)
    await closeWins(page)
  }
  // 2) the editor's calendar: two taps on two days
  await openNew(page, '2026-07-20')
  await page.selectOption('#inpEditType', 'Duty'); await page.selectOption('#inpEditPerson', ph)
  const ad2 = page.locator('#inpEditAllday'); if (await ad2.isChecked()) await ad2.uncheck()
  await setTimes(page, '09:00', '12:00'); await page.fill('#inpEditRmk', `walkS30 edcal ${ph}`)
  await page.locator('#inpEdCal [data-cal="2026-07-21"]').click(); await sleep(250)
  let n0 = await n(page)
  await page.locator('#inpEditSave').click(); await sleep(600)
  await pic(page, `s30-${ph}-3-editor-range`)
  note('S30-b editor calendar 20->21 Jul', ph, `saved ${await n(page) - n0} | OIL q ${await page.locator(T('oilconf')).isVisible().catch(() => false)} | messages: ${await msgs(page)}`)
  // 3) cross-month: editor opened on 31 Jul, one tap on 1 Aug
  await closeWins(page)
  await openNew(page, '2026-07-31')
  await page.selectOption('#inpEditType', 'Duty'); await page.selectOption('#inpEditPerson', ph)
  { const a = page.locator('#inpEditAllday'); if (await a.isChecked()) await a.uncheck() }
  await setTimes(page, '09:00', '12:00'); await page.fill('#inpEditRmk', `walkS30 xmonth ${ph}`)
  await page.locator('#inpEdCal button[aria-label="Next month"]').click(); await sleep(250)
  await page.locator('#inpEdCal [data-cal="2026-08-01"]').click(); await sleep(250)
  n0 = await n(page)
  await page.locator('#inpEditSave').click(); await sleep(600)
  await pic(page, `s30-${ph}-4-cross-month-jul-aug`)
  note('S30-c editor 31 Jul -> 1 Aug', ph, `saved ${await n(page) - n0} | OIL q ${await page.locator(T('oilconf')).isVisible().catch(() => false)} | messages: ${await msgs(page)}`)
  // 31 Dec -> 1 Jan: editor opened on Dec 31 (calendar moved to December first)
  await closeWins(page)
  await toMonth(page, 2026, 11)
  await openNew(page, '2026-12-31')
  await page.selectOption('#inpEditType', 'Duty'); await page.selectOption('#inpEditPerson', ph)
  { const a = page.locator('#inpEditAllday'); if (await a.isChecked()) await a.uncheck() }
  await setTimes(page, '09:00', '12:00'); await page.fill('#inpEditRmk', `walkS30 xyear ${ph}`)
  await page.locator('#inpEdCal button[aria-label="Next month"]').click(); await sleep(250)
  await page.locator('#inpEdCal [data-cal="2027-01-01"]').click(); await sleep(250)
  n0 = await n(page)
  await page.locator('#inpEditSave').click(); await sleep(600)
  await pic(page, `s30-${ph}-5-cross-year-dec-jan`)
  note('S30-d editor 31 Dec -> 1 Jan', ph, `saved ${await n(page) - n0} | OIL q ${await page.locator(T('oilconf')).isVisible().catch(() => false)} | messages: ${await msgs(page)}`)
  await closeWins(page)
  // 4) List Add form
  await listAll(page)
  await page.selectOption('#inType', 'Duty').catch(() => {}); await page.selectOption('#inPerson', ph).catch(() => {})
  await page.locator('#inCal [data-cal="2026-07-22"]').click(); await sleep(150); await page.locator('#inCal [data-cal="2026-07-23"]').click(); await sleep(250)
  await page.fill('#inRemarks', `walkS30 listadd ${ph}`)
  n0 = await n(page)
  await page.locator('#inAdd').click(); await sleep(600)
  await pic(page, `s30-${ph}-6-listadd-range`)
  note('S30-e List Add 22->23 Jul', ph, `saved ${await n(page) - n0} | OIL q ${await page.locator(T('oilconf')).isVisible().catch(() => false)} | messages: ${await msgs(page)}`)
  // cross-month in List Add
  await page.locator('#inCal [data-cal="2026-07-31"]').click(); await sleep(150)
  await page.locator('#inCal button[aria-label="Next month"]').first().click(); await sleep(250)
  await page.locator('#inCal [data-cal="2026-08-01"]').click(); await sleep(250)
  n0 = await n(page)
  await page.locator('#inAdd').click(); await sleep(600)
  note('S30-f List Add 31 Jul -> 1 Aug', ph, `saved ${await n(page) - n0} | messages: ${await msgs(page)}`)
  await pic(page, `s30-${ph}-7-listadd-crossmonth`)
  // 5) List pencil on a saved one-day input
  await closeWins(page)
  await page.locator('#inCalBtn').click(); await sleep(500)
  await fileInput(page, { iso: '2026-07-24', type: 'Duty', person: ph, remarks: `walkS30 pencil ${ph}`, start: '09:00', end: '12:00' }).catch(e => console.log('file for pencil failed', String(e).slice(0, 100)))
  await closeWins(page)
  await listAll(page); await listSearch(page, `walkS30 pencil ${ph}`)
  await pencil(page, `walkS30 pencil ${ph}`)
  await page.locator('tr.ined #inedCal [data-cal="2026-07-25"]').click(); await sleep(250)
  n0 = await n(page)
  await page.locator(PSAVE).click(); await sleep(600)
  note('S30-g List pencil: 24 Jul + tap 25 Jul', ph, `record still ${(await readInputs(page, `walkS30 pencil ${ph}`)).map(r => r.date || '')} | messages: ${await msgs(page)} | row stays open: ${await page.locator(PE).isVisible().catch(() => false)}`)
  await pic(page, `s30-${ph}-8-pencil-range`)
  await closeRowEdit(page)
  // 6) move a whole one-day bar to a different date (drag)
  await page.locator('#inCalBtn').click(); await sleep(500)
  await toMonth(page, 2026, 6)
  const barSel = `#inpCal .ib-bar[title*="walkS30 pencil ${ph}"], #inpCal .ib-bar[title*="24 Jul"]`
  const bar = page.locator('#inpCal .ib-bar').filter({ hasText: ph === 'all' ? /^ALL · Duty$/ : /ALL AVAIL · Duty/ }).filter({ has: page.locator('xpath=.') })
  const target = (await readInputs(page, `walkS30 pencil ${ph}`))[0]
  const barEl = page.locator(`[data-testid="ib-bar-${target.iid}"]`).first()
  const bb = await barEl.boundingBox(); const tb = await page.locator('#inpCal [data-icday="2026-07-27"]').boundingBox()
  console.log(ph, 'bar box', JSON.stringify(bb), 'target date box', JSON.stringify(tb))
  const cx = bb.x + bb.width / 2, cy = bb.y + bb.height / 2
  await page.mouse.move(cx, cy); await page.mouse.down()
  for (let i = 1; i <= 14; i++) await page.mouse.move(cx + (tb.x + 30 - cx) * i / 14, cy + (tb.y + 40 - cy) * i / 14)
  await page.mouse.up(); await sleep(700)
  const asked = await page.locator(T('oilconf')).isVisible().catch(() => false)
  const rec = (await readInputs(page, `walkS30 pencil ${ph}`))
  note('S30-h whole one-day bar moved 24 -> 27 Jul (Mon)', ph, `records: ${rec.length} | date now ${JSON.stringify(rec.map(r => r.date))} | OIL asked ${asked}`)
  await pic(page, `s30-${ph}-9-bar-moved`)
  // and to a weekend date: Sat 25 Jul
  const bb2 = await page.locator(`[data-testid="ib-bar-${target.iid}"]`).first().boundingBox(); const tb2 = await page.locator('#inpCal [data-icday="2026-07-26"]').boundingBox()
  const cx2 = bb2.x + bb2.width / 2, cy2 = bb2.y + bb2.height / 2
  await page.mouse.move(cx2, cy2); await page.mouse.down()
  for (let i = 1; i <= 14; i++) await page.mouse.move(cx2 + (tb2.x + 30 - cx2) * i / 14, cy2 + (tb2.y + 40 - cy2) * i / 14)
  await page.mouse.up(); await sleep(700)
  const asked2 = await page.locator(T('oilconf')).isVisible().catch(() => false)
  note('S30-i bar moved onto Sun 26 Jul', ph, `OIL question asked: ${asked2} | date ${JSON.stringify((await readInputs(page, `walkS30 pencil ${ph}`)).map(r => r.date))}`)
  await pic(page, `s30-${ph}-10-bar-moved-weekend`)
  if (asked2) await oilAnswer(page, 'yes')
  console.log(ph, 'after answer:', JSON.stringify((await readInputs(page, `walkS30 pencil ${ph}`)).map(r => ({ d: r.date, n: r.name, oil: r.oil }))))
  console.log(ph, 'errs', JSON.stringify(w.errs))
  await w.ctx.close()
}
await closeAll()
