// S4 - loading an issued version does not roll back issued money (desktop, admin)
const C = await import('./aa-C-lib.mjs')
const { world, fileInput, shot, board, sleep, go, pubSat, closeBoard, editWeek, face, fs, cr, crS, undoRedo, reload, dragPuckOff, pvBar, pvTap, lookAt, pend, pendListText, ROWS, row, saveRows } = C
const w = await world(); const { page } = w
const log = []
const say = (k, v) => { console.log(k, '::', typeof v === 'string' ? v : JSON.stringify(v)); log.push([k, v]) }
await fileInput(page, { iso: '2026-07-18', kind: 'Duty', person: 'allavail', s: '09:00', e: '12:00', rmk: 'S4 duty', oil: 'yes' })
await go(page, 'editsched'); await sleep(400)
await pubSat(page, 5); await closeBoard(page)
say('1 original issued', fs(await face(page)))
say('1 credits', crS(await cr(page)))
await shot(page, 'S4-01-original-issued')
// remove placeholder from its row on the board
await go(page, 'editsched'); await board(page, 5)
await dragPuckOff(page)
await shot(page, 'S4-02-puck-off')
await closeBoard(page)
say('2 after puck off', fs(await face(page)))
say('2 credits (still original)', crS(await cr(page)))
await go(page, 'editsched')
const p = await pubSat(page, 5); say('2 AL1 publish', p); await closeBoard(page)
say('3 AL1 issued', fs(await face(page)))
say('3 credits after AL1', crS(await cr(page)))
await shot(page, 'S4-03-al1-credits')
// preview Original, load onto working copy
await go(page, 'editsched'); await editWeek(page)
say('4 look Original', await lookAt(page, 5, /Original/))
say('4 bar', await pvBar(page, 5))
await shot(page, 'S4-04-preview-original')
await pvTap(page, 5, 'data-restore')
const b1 = await pvBar(page, 5); say('4 bar after Load', b1)
if (b1 && /confirm/i.test(b1.load || '')) { await pvTap(page, 5, 'data-restore'); say('4 bar after confirm', await pvBar(page, 5)) }
await shot(page, 'S4-05-after-load')
say('5 after load face', fs(await face(page)))
say('5 credits right after Load (expect still zero)', crS(await cr(page)))
say('5 pend list', await pendListText(page))
// working count back?
await go(page, 'editsched')
say('5 week puck/count', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="5"] .puck.allavail, #eWeek .day[data-day="5"] .oilcount')].map(e => e.innerText.trim())))
// replay check
say('6 undo', await undoRedo(page, 'undo'))
say('6 after undo', fs(await face(page)))
await shot(page, 'S4-06-after-undo')
say('6 undo puck', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="5"] .puck.allavail')].length))
say('6 redo', await undoRedo(page, 'redo'))
say('6 after redo', fs(await face(page)))
say('6 redo puck', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="5"] .puck.allavail')].length))
await reload(page); await go(page, 'editsched'); await sleep(400)
say('6 after reload', fs(await face(page)))
say('6 reload puck', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="5"] .puck.allavail')].length))
say('6 credits after reload', crS(await cr(page)))
await shot(page, 'S4-07-after-reload')
// view-only face
await go(page, 'viewsched'); await sleep(500)
say('7 view-only Sat', await page.evaluate(() => { const d = document.querySelector('#vWeek .day[data-day="5"]'); return { tag: (d.querySelector('.verchip') || {}).innerText, pucks: d.querySelectorAll('.puck.allavail').length, count: [...d.querySelectorAll('.oilcount')].map(e => e.innerText) } }))
await shot(page, 'S4-08-viewonly')
// publish the resulting AL
await go(page, 'editsched')
const p2 = await pubSat(page, 5); say('8 AL2 publish', p2); await closeBoard(page)
say('8 after AL2', fs(await face(page)))
say('8 credits after AL2', crS(await cr(page)))
await shot(page, 'S4-09-after-al2')
say('errors', w.errors)
await w.browser.close()
