// S5 - alternate plans keep their own placeholder rows and overrides (desktop, admin)
const C = await import('./aa-C-lib.mjs')
const { world, fileInput, shot, board, sleep, go, pubSat, closeBoard, editWeek, face, fs, cr, crS, undoRedo, reload, altPlan, switchTo, planMenuItems, pidOf, earnRead, pend, viewDay, pvBar, pvTap } = C
const w = await world(); const { page } = w
const say = (k, v) => console.log(k, '::', typeof v === 'string' ? v : JSON.stringify(v))
const ranger = await pidOf(page, 'Ranger')
const rows = async () => await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="5"] .pl-row, #eWeek .day[data-day="5"] .puck.allavail')].map(e => e.innerText.replace(/\s+/g, ' ').trim()).slice(0, 4))
await fileInput(page, { iso: '2026-07-18', kind: 'Duty', person: 'allavail', s: '09:00', e: '12:00', rmk: 'S5 duty', oil: 'yes' })
await go(page, 'editsched'); await sleep(300)
say('1 + Alt Plan', await altPlan(page, 5)); await sleep(400)
say('2 deny Ranger in Plan B (live)', await earnRead(page, [ranger], { tap: ranger }))
await closeBoard(page)
say('2 week rows (Plan B)', await rows())
// the view-only drafts picker (day not issued yet): look at Plan A
await go(page, 'viewsched'); await sleep(500)
const opts = await page.evaluate(() => [...document.querySelectorAll('#vWeek .day[data-day="5"] select')].map(s => ({ cls: s.className, opts: [...s.options].map(o => (o.selected ? '*' : '') + o.text + '=' + o.value) })))
say('3 view-only pickers', opts)
const dver = page.locator('#vWeek .day[data-day="5"] select[data-dver]').first()
if (await dver.count()) {
  const val = await dver.evaluate(s => [...s.options].find(o => o.value.startsWith('d:'))?.value)
  await dver.selectOption(val); await sleep(700)
  await shot(page, 'S5-01-viewonly-planA-preview')
  say('3 view-only bar', await page.evaluate(() => document.querySelector('#vWeek .day[data-day="5"] .dprev-bar')?.innerText))
}
await go(page, 'editsched'); await sleep(500)
say('3 edit bar', await pvBar(page, 5))
await shot(page, 'S5-02-edit-preview')
say('3 press Switch to this plan', await pvTap(page, 5, 'data-draftgo'))
await sleep(500)
say('3 after switch', fs(await face(page)))
say('3 plan menu', await planMenuItems(page, 5)); await page.keyboard.press('Escape')
say('3 Plan A earn state', await earnRead(page, [ranger])); await closeBoard(page)
// selector: to B and back to A
say('4 selector -> Plan B', await switchTo(page, 5, /Plan B/)); await sleep(400)
say('4 B earn', await earnRead(page, [ranger])); await closeBoard(page)
say('4 selector -> Plan A', await switchTo(page, 5, /Plan A/)); await sleep(400)
say('4 A earn', await earnRead(page, [ranger])); await closeBoard(page)
await go(page, 'editsched')
say('5 issue plan A', await pubSat(page, 5)); await closeBoard(page)
say('5 face', fs(await face(page)))
say('5 credits (Plan A issued)', crS(await cr(page)))
await go(page, 'editsched')
say('6 selector -> Plan B on a published day', await switchTo(page, 5, /Plan B/)); await sleep(500)
say('6 face', fs(await face(page)))
say('6 credits after switch (issued unchanged)', crS(await cr(page)))
await go(page, 'editsched')
say('6 B earn', await earnRead(page, [ranger])); await closeBoard(page)
await shot(page, 'S5-03-planB-published-day')
// replay check
say('7 undo', await undoRedo(page, 'undo'))
say('7 after undo', fs(await face(page))); say('7 earn', await earnRead(page, [ranger])); await closeBoard(page)
say('7 credits after undo', crS(await cr(page)))
await go(page, 'editsched')
say('7 redo', await undoRedo(page, 'redo'))
say('7 after redo', fs(await face(page))); say('7 earn', await earnRead(page, [ranger])); await closeBoard(page)
await reload(page); await go(page, 'editsched'); await sleep(400)
say('7 after reload', fs(await face(page)))
say('7 reload earn', await earnRead(page, [ranger])); await closeBoard(page)
say('7 credits after reload', crS(await cr(page)))
await go(page, 'editsched')
// issue the selected plan (B, Ranger denied)
say('8 issue Plan B as AL1', await pubSat(page, 5)); await closeBoard(page)
say('8 face', fs(await face(page)))
say('8 credits after AL1 (Ranger 0, others HO expected)', crS(await cr(page)))
await shot(page, 'S5-04-final-credits')
say('errors', w.errors)
await w.browser.close()
