// S20 part A - roster changes use the date: archive Ranger (posted out from today = 9 Oct 26) after a July issue
const C = await import('./aa-C-lib.mjs')
const { world, shot, sleep, go, fileInput, pubSat, closeBoard, editWeek, face, fs, cr, crS, signDay, pidOf, undoRedo, reload, jumpWeek, archivePerson, earnRead } = C
const say = (k, v) => console.log(k, '::', typeof v === 'string' ? v : JSON.stringify(v))
const w = await world(); const { page } = w
const ranger = await pidOf(page, 'Ranger')
const ctrl = ['Saber', 'Basher', 'Ace']
await fileInput(page, { iso: '2026-07-18', kind: 'Duty', person: 'allavail', s: '09:00', e: '12:00', rmk: 'S20 july', oil: 'yes' })
await fileInput(page, { iso: '2026-10-10', kind: 'Duty', person: 'allavail', s: '09:00', e: '12:00', rmk: 'S20 oct', oil: 'yes' })
await go(page, 'editsched'); await pubSat(page, 5); await closeBoard(page)
say('1 July issued', fs(await face(page, 5))); say('1 July credits', crS(await cr(page, '2026-07-18')))
await jumpWeek(page, '2026-10-10'); await sleep(500)
await shot(page, 'S20-01-october-week')
say('2 Oct week Sat face (working)', fs(await face(page, 5)))
say('2 Oct Sat crowd earn', await earnRead(page, [ranger]))
await closeBoard(page)
await go(page, 'editsched'); say('2 publish Oct 10', await pubSat(page, 5)); await closeBoard(page)
say('2 Oct 10 issued', fs(await face(page, 5))); say('2 Oct credits (Ranger HO)', crS(await cr(page, '2026-10-10')))
// archive
say('3 undo button before archive', await page.evaluate(() => { const b = document.querySelector('#undoBtn'); return b ? { disabled: b.disabled, title: b.title } : null }))
await archivePerson(page, ranger)
say('3 undo button after archive', await page.evaluate(() => { const b = document.querySelector('#undoBtn'); return b ? { disabled: b.disabled, title: b.title } : null }))
await shot(page, 'S20-02-archived')
await go(page, 'editsched'); await sleep(500)
say('4 Oct 10 face after archive (working crowd, pending?)', fs(await face(page, 5))); say('4 Oct credits (issued: Ranger HO until AL)', crS(await cr(page, '2026-10-10')))
await go(page, 'editsched'); say('4 Oct earn window', await earnRead(page, [ranger])); await closeBoard(page)
await jumpWeek(page, '2026-07-18'); await sleep(500)
say('5 July face after archive (no crowd-only pending expected)', fs(await face(page, 5))); say('5 July credits (Ranger HO kept)', crS(await cr(page, '2026-07-18')))
say('5 July earn window (Ranger still in the frozen crowd?)', await earnRead(page, [ranger])); await closeBoard(page)
await shot(page, 'S20-03-july-after-archive')
await reload(page); await go(page, 'editsched'); await sleep(300)
say('6 after reload July face', fs(await face(page, 5))); say('6 July credits', crS(await cr(page, '2026-07-18')))
await jumpWeek(page, '2026-10-10'); await sleep(400)
say('6 after reload Oct face', fs(await face(page, 5))); say('6 Oct credits', crS(await cr(page, '2026-10-10')))
await jumpWeek(page, '2026-10-10'); say('7 AL1 for Oct 10', await pubSat(page, 5)); await closeBoard(page)
say('7 Oct face', fs(await face(page, 5))); say('7 Oct credits (Ranger loses HO)', crS(await cr(page, '2026-10-10')))
await shot(page, 'S20-04-oct-al1')
say('errors', w.errors); await w.browser.close()
