import { chromium, launchOptions, world, shot, tid, cell, typeReq, backToSans, readDate, readDayWin, fileCommit, press } from './cal-D-lib.mjs'
const browser = await chromium.launch(launchOptions)
const { ctx, page, errors } = await world(browser, 'desk')
const f = await page.evaluate(() => window.lwDayFacts('2026-07-20')); console.log(JSON.stringify(f))
await typeReq(page, 'desk', 'req-p', '2026-07-20', f.availP + 4); await page.keyboard.press('Escape')
await typeReq(page, 'desk', 'req-w', '2026-07-20', f.availW + 3); await page.keyboard.press('Escape')
await backToSans(page, 'desk')
console.log(JSON.stringify(await readDate(page, '2026-07-20')))
await cell(page, '2026-07-20').click({ position: { x: 8, y: 8 } })
await tid(page, 'win-sansday').waitFor()
console.log(JSON.stringify(await readDayWin(page)))
await shot(page, 'p401-0-day-before')
await fileCommit(page, 'desk', 'vinci', { f: true })
await shot(page, 'p401-1-editor')
await page.click('#inpEditSave'); await page.waitForTimeout(500)
console.log(JSON.stringify(await readDate(page, '2026-07-20')))
console.log(JSON.stringify(await readDayWin(page)))
await shot(page, 'p401-2-after-file')
console.log(errors.join('\n'))
await ctx.close(); await browser.close()
