import * as L from './cal-F-lib2.mjs'
const b = await L.launch()
const ctx = await L.newCtx(b)
const p = await L.newPage(ctx)
await L.signIn(p, 'ad')
await L.go(p, 'inputs')
await L.toastSpy(p)
const [ace, anvil, basher] = await L.ids(p, ['Ace', 'Anvil', 'Basher'])
const save = () => p.locator('#inpEditSave').click()
await L.openNew(p, '2026-07-21')
await p.selectOption('#inpEditPerson', ace)
await p.selectOption('#inpEditType', 'LL')
let had = await L.iidSet(p)
await save(); await L.sleep(500)
console.log('fixture', JSON.stringify(await L.newRows(p, had)))
// shared: do NOT touch dates; the day cell opened 21 Jul preselected
await L.openNew(p, '2026-07-21')
await p.selectOption('#inpEditType', 'LL')
await L.pickSeveral(p, [ace, anvil, basher])
console.log('dates label', await p.locator('#inpEditSpan').innerText().catch(() => 'n/a'))
await L.pic(p, 'c-form')
had = await L.iidSet(p)
await L.toasts(p)
await save(); await L.sleep(300)
console.log('toasts', JSON.stringify(await L.toasts(p)))
console.log('new rows', JSON.stringify((await L.newRows(p, had)).map(r => [r.person, r.type, r.date, r.endDate])))
await L.pic(p, 'c-after')
await b.close()
