import { world, toLeaveWar, toInputs, tid, press, pic, sleep, closeAll, openWins, active } from './cal-C-lib.mjs'
const { page, errors } = await world('desk')
await toLeaveWar(page)
await pic(page, 'recon-lw')
await tid(page, 'settings-open').click()
await sleep(300)
await pic(page, 'recon-lw-settings')
console.log('testids:', await page.evaluate(() => [...new Set([...document.querySelectorAll('[data-testid]')].map(e => e.getAttribute('data-testid')))].filter(x => !/^(cell|row|day|col)/.test(x)).slice(0, 150)))
await tid(page, 'settings-days').click()
await tid(page, 'win-days').waitFor()
await sleep(300)
await pic(page, 'recon-days')
console.log('wins', await openWins(page), await active(page))
console.log('days testids:', await page.evaluate(() => [...document.querySelectorAll('[data-testid]')].map(e => e.getAttribute('data-testid')).filter(x => /^(days|hol|every)/.test(x)).slice(0, 80)))
console.log(errors)
await closeAll()
