/* WALKER F — P6-05, finding F2: the foot of a filer's own saved group entry when the members' switch is OFF. */
import * as L from './cal-F-lib3.mjs'
const b = await L.launch()
const ctx = await L.newCtx(b)
const p = await L.newPage(ctx)
await L.signIn(p, 'ad')
await L.go(p, 'inputs')
await L.toastSpy(p)
const [ranger, echo, saber] = await L.ids(p, ['Ranger', 'Echo', 'Saber'])
await L.be(p, ranger, 'member')
await L.openNew(p, '2026-07-31')
await p.selectOption('#inpEditType', 'Meeting')
await L.pickSeveral(p, [ranger, echo])
await L.setWhen(p, { allday: true, remarks: 'p605c one' })
await p.locator('#inpEditSave').click(); await L.sleep(700)
await L.be(p, saber, 'admin')
await p.locator('[data-testid="in-gear"]').click(); await L.sleep(500)
await p.locator('[data-testid="iset-memberfile"]').setChecked(false)
await p.locator('[data-testid="iset-save"]').click(); await L.sleep(600)
await L.be(p, ranger, 'member')
if (await p.locator('[data-testid="win-inputsday-x"]').count()) await p.locator('[data-testid="win-inputsday-x"]').click()
await p.locator('#inpCal .ib-bar').filter({ hasText: '+1' }).first().click(); await L.sleep(700)
const foot = await p.evaluate(() => {
  const w = document.querySelector('[data-testid="win-inputedit"]')
  const sc = [...w.querySelectorAll('*')].find(e => e.scrollHeight > e.clientHeight + 4 && getComputedStyle(e).overflowY !== 'visible')
  if (sc) sc.scrollTop = sc.scrollHeight
  const ro = w.querySelector('[data-testid="inped-ro"]')
  return { scroller: sc ? (sc.className || sc.tagName) : null, ro: ro ? ro.innerText : null, buttons: [...w.querySelectorAll('button')].filter(x => x.offsetParent !== null).map(x => x.innerText.trim()).filter(Boolean).slice(-6) }
})
await L.sleep(300)
await p.locator('[data-testid="win-inputedit"]').screenshot({ path: L.SHOTS + '/zz-p605c-foot.png' })
console.log(JSON.stringify(foot))
await L.pic(p, 'p605c-foot-of-window')
await b.close()
