import { chromium, launchOptions, world, shot, tid, cell, backToSans, readDate, readDayWin, press, isTouch } from './cal-D-lib.mjs'
const browser = await chromium.launch(launchOptions)
const size = 'desk'
const { ctx, page, errors } = await world(browser, size)
await backToSans(page, size)
const ISO = '2026-07-22'
console.log('before', JSON.stringify(await readDate(page, ISO)))
await press(size, cell(page, ISO), { position: { x: 8, y: 8 } }); await tid(page, 'win-sansday').waitFor()
await press(size, tid(page, 'sd-add')); await page.waitForSelector('#inpEditSave')
await page.locator('#inpEditPop [data-testid="pp-several"]').click(); await page.waitForTimeout(250)
for (const id of ['yeti', 'cards', 'badger']) await page.locator(`#inpEditPop [data-pp="${id}"]`).click()
await page.locator('#inpEditSans').getByLabel('Fly', { exact: true }).check()
await page.locator('#inpEditSans').getByLabel('OFT', { exact: true }).check()
console.log('count line', await page.locator('#inpEditPop [data-testid="pp-count"]').innerText())
await shot(page, 'h06-2-picked')
await page.click('#inpEditSave'); await page.waitForTimeout(600)
console.log('editor open after save', await page.locator('#inpEditSave').isVisible().catch(() => false), 'msgs', (await page.evaluate(() => ((document.querySelector('#inpEditPop') || {}).innerText || '').slice(0, 300))))
console.log('after', JSON.stringify(await readDate(page, ISO)))
const w = await readDayWin(page); console.log(JSON.stringify(w))
await shot(page, 'h06-3-day')
console.log('idy-people?', await page.locator('[data-testid="win-sansday"] [data-testid="idy-people"]').count())
// open the entry's editor from one of its rows
const row = page.locator('[data-testid="win-sansday"] [data-testid^="sd-row-"]').first()
await press(size, row.locator('[data-testid="sd-open"]')); await page.waitForTimeout(500)
await shot(page, 'h06-4-editor')
console.log('EDITOR:', await page.evaluate(() => (document.querySelector('#inpEditPop') || {}).innerText.replace(/\s+/g, ' ').slice(0, 900)))
console.log('buttons:', await page.evaluate(() => [...document.querySelectorAll('#inpEditPop button')].map(b => (b.id || b.getAttribute('data-testid') || '') + ':' + b.innerText.replace(/\s+/g, ' ')).join(' | ')))
await page.keyboard.press('Escape')
console.log(errors.join('|'))
await ctx.close(); await browser.close()
