import { chromium, launchOptions, world, shot, tid, cell, backToSans, readDate, readDayWin, press, isTouch } from './cal-D-lib.mjs'
const browser = await chromium.launch(launchOptions)
const size = process.argv[2] || 'desk'
const { ctx, page, errors } = await world(browser, size)
await backToSans(page, size)
const ISO = '2026-07-17'
const L = (...a) => console.log(size, ...a)
L('before', JSON.stringify(await readDate(page, ISO)))
await press(size, cell(page, ISO), { position: { x: 8, y: 8 } }); await tid(page, 'win-sansday').waitFor()
await press(size, tid(page, 'sd-add')); await page.waitForSelector('#inpEditSave')
await page.locator('#inpEditPop [data-testid="pp-several"]').click(); await page.waitForTimeout(250)
for (const id of ['yeti', 'cards', 'badger']) await press(size, page.locator(`#inpEditPop [data-pp="${id}"]`))
await press(size, page.locator('#inpEditPop [data-pp="vinci"]'))     // the default man is lit at first: untick him
L('count line', await page.locator('#inpEditPop [data-testid="pp-count"]').innerText())
await page.locator('#inpEditSans').getByLabel('Fly', { exact: true }).check()
await page.locator('#inpEditSans').getByLabel('OFT', { exact: true }).check()
await shot(page, `h06-${size}-picked`)
await page.click('#inpEditSave'); await page.waitForTimeout(600)
L('after', JSON.stringify(await readDate(page, ISO)))
let w = await readDayWin(page); L('day rows', JSON.stringify(w.rows), 'groups', JSON.stringify(w.groups), w.work)
await shot(page, `h06-${size}-day`)
// the changes window (Edit Schedule, the clock)
await page.evaluate(() => window.go('editsched')); await page.waitForTimeout(900)
await page.click('#histBtn'); await page.waitForTimeout(700)
const cw = await page.evaluate(() => { const w = document.querySelector('.floatwin[data-testid="win-changes"], [data-testid="win-changes"], #chgWin, .chgwin, [class*=changes]'); return w ? w.innerText.replace(/\s+/g, ' ').slice(0, 1200) : document.body.innerText.slice(0, 200) })
L('CHANGES WINDOW:', cw)
await shot(page, `h06-${size}-changes`)
await page.getByText('All changes', { exact: false }).first().click(); await page.waitForTimeout(500)
L('ALL CHANGES:', await page.evaluate(() => { const w = [...document.querySelectorAll('[data-testid]')].find(e => /win-chang|chg/i.test(e.getAttribute('data-testid'))); return (w || document.body).innerText.replace(/s+/g, ' ').slice(0, 1500) }))
await shot(page, `h06-${size}-changes-all`)
await page.getByText('Who', { exact: true }).first().click().catch(() => {}); await page.waitForTimeout(400)
L('BY WHO:', await page.evaluate(() => document.body.innerText.replace(/s+/g, ' ').slice(0, 100)))
await shot(page, `h06-${size}-changes-who`)
console.log(errors.join('|'))
await ctx.close(); await browser.close()
