import { launch, open, openDay, press, shot, cardFacts, toList, overflow, judge, saveRows, geom2, saveWin, csId, DAYWIN, WIN, rec, recAll, errs } from './icard-A-lib.mjs'
const browser = await launch()
const T = true
const { ctx, page: p } = await open(browser, { width: 390, height: 844 }, 'ad', 'a', T)
await openDay(p, '2026-07-21', T)
await press(T, p.locator('#icPopAdd')); await p.locator(WIN).waitFor()
await p.selectOption('#inpEditType', 'ATT C'); await p.selectOption('#inpEditPerson', await csId(p, 'Hex'))
await saveWin(p, T, 'no')
const down = await rec(p, { type: 'ATT C', person: await csId(p, 'Hex') })
console.log('downchit', JSON.stringify(down))
await p.keyboard.press('Escape'); await p.waitForTimeout(300)
await p.evaluate(() => window.go('inputs'))
await press(T, p.locator('#inMedBtn')); await p.waitForTimeout(500)
await press(T, p.locator('#medCalBtn')); await p.waitForTimeout(400)
await p.locator('.medcal-day:has-text("22"), [data-medday="2026-07-22"]').first().tap(); await p.waitForTimeout(500)
await p.locator('.medcard').filter({ hasText: 'Hex' }).first().tap(); await p.waitForTimeout(600)
await shot(p, '11-phone-medical-sheet')
await p.locator('button:has-text("Upchit")').last().tap(); await p.waitForTimeout(700)
await p.fill('#inpEditUpDate', '2026-07-22')
await p.locator('#inpEditSave').tap(); await p.waitForTimeout(700)
await p.locator('[data-testid="docconf-nodoc"]').tap(); await p.waitForTimeout(700)
const summary = (await p.locator('body').innerText()).split('Upchit — Hex').pop()
const sumpic = await shot(p, '11-phone-upchit-summary')
await p.locator('[data-testid="upconf-save"]').tap(); await p.waitForTimeout(800)
const up = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
console.log('upchit', JSON.stringify(up), 'summary:', summary.replace(/\s+/g, ' ').slice(0, 300))
const probs = []
if (!up) probs.push('the upchit was not saved')
// find it in Inputs: the phone list
await toList(p, T)
const cards = await cardFacts(p, '#inList', 'inl')
const c = cards.find(x => up && x.iid === up.iid)
const downCard = cards.find(x => down && x.iid === down.iid)
let g = null
if (!c) probs.push('no list card for the upchit')
else {
  if (c.who !== 'Hex') probs.push('who ' + c.who)
  if ((c.kind || '').toLowerCase() !== 'upchit') probs.push('kind ' + c.kind)
  if (c.tone !== 'amb') probs.push(`square ${c.tone} (${c.sqColor}), wanted amber`)
  if (c.late) probs.push('has a LATE tag')
  if (c.title) probs.push('has a title "' + c.title + '"')
  g = await geom2(p, `#inList [data-testid="inl-row-${up.iid}"]`)
  if (g.probs.length) probs.push(g.probs.join(','))
  const head = await p.evaluate(iid => { let e = document.querySelector(`#inList [data-iid="${iid}"]`) || document.querySelector(`#inList [data-testid="inl-row-${iid}"]`); while (e && !e.matches('[data-testid="inl-day"]')) e = e.previousElementSibling; return e ? e.textContent.replace(/\s+/g, ' ') : null }, up.iid)
  console.log('heading', head)
  if (!/Wed 22 Jul/i.test(head || '')) probs.push('day heading "' + head + '"')
  await p.locator(`#inList [data-testid="inl-row-${up.iid}"]`).scrollIntoViewIfNeeded()
  var listpic = await shot(p, '11-phone-list-upchit')
}
console.log('list card', JSON.stringify(c), 'downchit card', downCard && JSON.stringify({ kind: downCard.kind, tone: downCard.tone, late: downCard.late }))
// the opened day
await openDay(p, '2026-07-22', T); await p.waitForTimeout(400)
const dcards = await cardFacts(p, DAYWIN, 'idy')
const dc = dcards.find(x => up && x.iid === up.iid)
if (!dc) probs.push('no card on the opened day 22 Jul')
else { if (dc.tone !== 'amb') probs.push('day card square ' + dc.tone); if (dc.late) probs.push('day card LATE'); if (dc.title) probs.push('day card title') ; if ((dc.kind || '').toLowerCase() !== 'upchit') probs.push('day card kind ' + dc.kind) }
const daypic = await shot(p, '11-phone-day-upchit')
await p.keyboard.press('Escape'); await p.waitForTimeout(300)
// Undo / Redo
await press(T, p.locator('#undoBtn')); await p.waitForTimeout(600)
const afterUndo = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
await press(T, p.locator('#redoBtn')); await p.waitForTimeout(600)
const afterRedo = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
console.log('undo ->', !!afterUndo, 'redo ->', !!afterRedo)
if (afterUndo) probs.push('Undo did not remove the upchit'); if (!afterRedo) probs.push('Redo did not restore the upchit')
judge(11, 'phone 390', 'admin', probs.length ? 'FAIL' : 'PASS', probs.join(' | ') || `upchit for Hex: UPCHIT in grey capitals, amber square, under WED 22 JUL, no LATE, no title (day card likewise); the downchit stays an absence card; Undo/Redo fine. Summary read: ${summary.replace(/\s+/g, ' ').slice(0, 160)}`, ['11-phone-medical-sheet.png', sumpic, listpic, daypic].filter(Boolean))
await ctx.close()
await browser.close()
saveRows('s11')
console.log('ERRS', JSON.stringify(errs))
