import { launch, open, openDay, press, shot, cardFacts, toList, overflow, judge, saveRows, geom2, saveWin, csId, DAYWIN, WIN, rec, recAll, errs } from './icard-A-lib.mjs'
const browser = await launch()
const T = false
const { ctx, page: p } = await open(browser, { width: 1440, height: 900 }, 'ad', 'a', T)
const probs = []
// read the cut-off setting
await p.evaluate(() => window.go('inputs'))
await p.locator('#inGear').click(); await p.waitForTimeout(500)
const gear = (await p.locator('body').innerText()).split('LATE CUT-OFF FOR INPUTS').pop().split('FILING FOR OTHER')[0].split('\n').join(' ').replace(/\s+/g, ' ').trim()
console.log('GEAR', gear)
const gpic = await shot(p, '14-desk-cutoff-setting')
await p.keyboard.press('Escape'); await p.waitForTimeout(300)
if (await p.locator('[data-testid^="win-"]').count()) { for (const x of await p.locator('[data-testid$="-x"]:visible').all()) await x.click().catch(() => {}) }
// file a Duty (Anvil, Tue 21 Jul), a downchit (Hex, Tue 21 Jul) and its upchit (Wed 22 Jul)
await openDay(p, '2026-07-21', T)
await press(T, p.locator('#icPopAdd')); await p.locator(WIN).waitFor()
await p.selectOption('#inpEditType', 'Duty'); await p.selectOption('#inpEditPerson', await csId(p, 'Anvil')); await p.fill('#inpEditStart', '09:00'); await p.fill('#inpEditEnd', '10:00')
await saveWin(p, T, 'no')
await press(T, p.locator('#icPopAdd')); await p.locator(WIN).waitFor()
await p.selectOption('#inpEditType', 'ATT C'); await p.selectOption('#inpEditPerson', await csId(p, 'Hex'))
await saveWin(p, T, 'no')
const duty = await rec(p, { type: 'Duty', person: await csId(p, 'Anvil') }), down = await rec(p, { type: 'ATT C', person: await csId(p, 'Hex') })
await p.keyboard.press('Escape'); await p.waitForTimeout(300)
await p.evaluate(() => window.go('inputs'))
await p.locator('#inMedBtn').click(); await p.waitForTimeout(500)
await p.locator('#medCalBtn').click(); await p.waitForTimeout(300)
await p.locator('.medcal-day:has-text("22"), [data-medday="2026-07-22"]').first().click(); await p.waitForTimeout(500)
await p.locator('.medcard').filter({ hasText: 'Hex' }).first().click(); await p.waitForTimeout(500)
await p.locator('button:has-text("Upchit")').last().click(); await p.waitForTimeout(600)
await p.fill('#inpEditUpDate', '2026-07-22')
await p.locator('#inpEditSave').click(); await p.waitForTimeout(600)
await p.locator('[data-testid="docconf-nodoc"]').click(); await p.waitForTimeout(600)
await p.locator('[data-testid="upconf-save"]').click(); await p.waitForTimeout(700)
const up = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
console.log('records', !!duty, !!down, !!up)
if (!duty || !down || !up) probs.push('a fixture was not filed: ' + JSON.stringify({ duty: !!duty, down: !!down, up: !!up }))
// the opened day 21 Jul
await openDay(p, '2026-07-21', T); await p.waitForTimeout(400)
const cards = await cardFacts(p, DAYWIN, 'idy')
const cd = cards.find(c => duty && c.iid === duty.iid), cm = cards.find(c => down && c.iid === down.iid)
if (!cd || !cd.late) probs.push('the Duty has no LATE button'); if (!cm) probs.push('no ATT C card'); else if (cm.late) probs.push('the downchit carries a LATE tag')
const card = p.locator(`${DAYWIN} [data-testid="idy-row-${duty.iid}"]`)
const before = await shot(p, '14-desk-day-before-late')
await card.locator('[data-testid="idy-late"]').click(); await p.waitForTimeout(250)
const note = await card.locator('[data-testid="idy-latenote"]').innerText().catch(() => null)
const exp1 = await card.locator('[data-testid="idy-late"]').getAttribute('aria-expanded')
const editorOpen = await p.locator(WIN).count()
const during = await shot(p, '14-desk-day-late-pressed')
console.log('note', note, 'expanded', exp1, 'editor open', editorOpen)
if (note !== 'after the cut-off, Mon 6 Jul') probs.push(`the LATE note says "${note}" (the setting is 14 days before the week starts, on a Monday: the week of Mon 20 Jul is due by Mon 6 Jul)`)
if (editorOpen) probs.push('pressing LATE opened the editor')
await card.locator('[data-testid="idy-late"]').click(); await p.waitForTimeout(250)
const note2 = await card.locator('[data-testid="idy-latenote"]').count(); const exp2 = await card.locator('[data-testid="idy-late"]').getAttribute('aria-expanded')
const editor2 = await p.locator(WIN).count()
console.log('after 2nd press: note count', note2, 'expanded', exp2, 'editor', editor2)
if (note2) probs.push('the second press did not close the explanation'); if (editor2) probs.push('the second press opened the editor')
const after = await shot(p, '14-desk-day-late-closed')
// 22 Jul: the upchit; the table: LATE only on the Duty row
await openDay(p, '2026-07-22', T); await p.waitForTimeout(300)
const uc = (await cardFacts(p, DAYWIN, 'idy')).find(c => up && c.iid === up.iid)
if (!uc) probs.push('no upchit card'); else if (uc.late) probs.push('the upchit carries a LATE tag')
await toList(p, T)
const late = await p.evaluate(ids => ids.map(i => { const tr = document.querySelector(`#inBody tr[data-iid="${i}"]`); return tr ? /LATE/.test(tr.innerText) : null }), [duty.iid, down.iid, up.iid])
console.log('table LATE tags (duty, down, up)', late)
if (late[0] !== true) probs.push('table row of the Duty has no LATE'); if (late[1] || late[2]) probs.push('a medical row carries LATE in the table')
const tpic = await shot(p, '14-desk-table')
// undo / redo (main save = the upchit)
await p.locator('#undoBtn').click(); await p.waitForTimeout(500)
const u1 = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
await p.locator('#redoBtn').click(); await p.waitForTimeout(500)
const u2 = await rec(p, { type: 'Upchit', person: await csId(p, 'Hex') })
if (u1) probs.push('Undo did not take back the upchit'); if (!u2) probs.push('Redo did not restore the upchit')
judge(14, 'desktop 1440', 'admin', probs.length ? 'FAIL' : 'PASS', probs.join(' | ') || `setting: ${gear.slice(0, 200)}; Duty LATE pressed -> "${note}", editor not opened, 2nd press closed it; downchit and upchit cards and rows carry no LATE; Undo/Redo fine`, [gpic, before, during, after, tpic])
await ctx.close()
await browser.close()
saveRows('s14')
console.log('ERRS', JSON.stringify(errs))
