import { launch, open, openDay, press, shot, cardFacts, toList, overflow, judge, saveRows, geom2, saveWin, csId, dayHeads, DAYWIN, WIN, rec, recAll, errs } from './icard-A-lib.mjs'
const browser = await launch()
const T = true
const { ctx, page: p } = await open(browser, { width: 390, height: 844 }, 'ad', 'a', T)
const probs = []; const pics = []; const notes = []
// A: Tue 12 Jan 2027
await openDay(p, '2027-01-12', T)
await press(T, p.locator('#icPopAdd')); await p.locator(WIN).waitFor()
await p.selectOption('#inpEditType', 'Meeting'); await p.selectOption('#inpEditPerson', await csId(p, 'Anvil'))
await p.fill('#inpEditStart', '09:00'); await p.fill('#inpEditEnd', '10:00'); await p.fill('#inpEditOwnTitle', 'Year-ahead brief')
await saveWin(p, T, 'no')
const A = await rec(p, { title: 'Year-ahead brief' })
console.log('A', JSON.stringify(A))
// B: Mon 28 Dec 2026 -> Fri 1 Jan 2027
await p.keyboard.press('Escape'); await p.waitForTimeout(250)
await openDay(p, '2026-12-28', T)
await press(T, p.locator('#icPopAdd')); await p.locator(WIN).waitFor()
await p.selectOption('#inpEditType', 'Duty'); await p.selectOption('#inpEditPerson', await csId(p, 'Basher'))
await p.fill('#inpEditStart', '09:00'); await p.fill('#inpEditEnd', '10:00'); await p.fill('#inpEditOwnTitle', 'Year-turn duty')
const nav = p.locator(`${WIN} #inpEdCal`).locator('button').filter({ hasText: '›' }).first()
await nav.scrollIntoViewIfNeeded(); await nav.tap(); await p.waitForTimeout(250)
const cell = p.locator(`${WIN} #inpEdCal [data-cal="2027-01-01"]`); await cell.scrollIntoViewIfNeeded(); await cell.tap()
const readLine = await p.locator(`${WIN} .rc-read`).innerText().catch(() => '')
console.log('B line under the calendar:', readLine)
await saveWin(p, T, 'no')
const B = await rec(p, { title: 'Year-turn duty' })
console.log('B', JSON.stringify(B))
if (!A) probs.push('January input not saved'); if (!B || B.endDate == null) probs.push('cross-year input not saved as a range: ' + JSON.stringify(B))
// the phone list
await p.keyboard.press('Escape'); await p.waitForTimeout(250)
await toList(p, T)
const heads = await dayHeads(p)
const cards = await cardFacts(p, '#inList', 'inl')
const ca = cards.find(c => A && c.iid === A.iid), cb = cards.find(c => B && c.iid === B.iid)
const under = await p.evaluate(ids => ids.map(i => { let e = document.querySelector(`#inList [data-testid="inl-row-${i}"]`); while (e && !e.matches('[data-testid="inl-day"]')) e = e.previousElementSibling; return e ? e.textContent.replace(/\s+/g, ' ') : null }), [A && A.iid, B && B.iid])
console.log('headings', JSON.stringify(under), '| corners', ca && ca.when, '|', cb && cb.when)
console.log('all headings with a year', JSON.stringify(heads.filter(h => /\d{4}/.test(h.t))), 'others', heads.filter(h => !/\d{4}/.test(h.t)).length)
if (!/2027/.test(under[0] || '')) probs.push(`January's heading has no year: "${under[0]}"`)
if (!cb || !/till 1 Jan 2027/.test(cb.when)) probs.push(`the cross-year corner says "${cb && cb.when}", not "till 1 Jan 2027"`)
// the 2026 heading of B and the list pictures
await p.locator(`#inList [data-testid="inl-row-${B.iid}"]`).scrollIntoViewIfNeeded(); pics.push(await shot(p, '17-phone-list-cross-year'))
await p.locator(`#inList [data-testid="inl-row-${A.iid}"]`).scrollIntoViewIfNeeded(); pics.push(await shot(p, '17-phone-list-january'))
// opening each: its month and year
for (const [lab, r, want, wantMon] of [['january', A, /12 Jan 2027|Jan 12, 2027|12 Jan/, /JAN 2027/i], ['cross-year', B, /28 Dec/, /DEC 2026/i]]) {
  const c = p.locator(`#inList [data-testid="inl-row-${r.iid}"]`); await c.scrollIntoViewIfNeeded(); await c.tap(); await p.locator(WIN).waitFor()
  const w = await p.evaluate(() => ({ head: (document.querySelector('[data-testid="win-inputedit"] .win-ttl') || {}).textContent, mon: ((document.querySelector('#inpEdCal') || {}).innerText || '').split('\n').filter(x => /20\d\d/.test(x)).join(' '), read: (document.querySelector('#inpEdCal ~ .rc-read, .rc-read') || {}).textContent }))
  pics.push(await shot(p, `17-phone-window-${lab}`))
  console.log(lab, JSON.stringify(w))
  if (!wantMon.test(w.mon)) probs.push(`${lab}: the window's calendar shows "${w.mon}"`)
  if (/2026/.test(w.head || '') === false && lab === 'january' && !/2027/.test(w.head || '')) notes.push(`${lab} window title "${w.head}" carries no year`)
  if (lab === 'january' && /Jul/.test(w.mon)) probs.push('window shows the loaded July')
  await press(T, p.locator('#inpEditCancel')); await p.waitForTimeout(250)
}
// undo / redo of the main save (the last one: B)
await press(T, p.locator('#undoBtn')); await p.waitForTimeout(450)
const gone = !(await rec(p, { title: 'Year-turn duty' }))
await press(T, p.locator('#redoBtn')); await p.waitForTimeout(450)
const back = await rec(p, { title: 'Year-turn duty' })
if (!gone || !back || back.endDate !== B.endDate) probs.push(`Undo/Redo of the cross-year input: gone ${gone}, back ${!!back} ${back && back.date + '>' + back.endDate}`)
judge(17, 'phone 390', 'admin', probs.length ? 'FAIL' : 'PASS', probs.join(' | ') || `list headings ${JSON.stringify(under)}, corners "${ca.when}" / "${cb.when}"; both windows open on their own month and year; ${notes.join(' ; ')}`, pics)
await ctx.close()
await browser.close()
saveRows('s17')
console.log('ERRS', JSON.stringify(errs))
