// Writes walker A's hand-back: docs/handpass/parts/it-A.json from the per-scenario rows (the md is written by it-A-md.mjs).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { ROWS_DIR } from './it-A-lib.mjs'
const rows = []
for (const f of readdirSync(ROWS_DIR).filter(f => /^rows-s\d+\.json$/.test(f))) rows.push(...JSON.parse(readFileSync(join(ROWS_DIR, f), 'utf8')))
const P = n => n + '.png'
const L = (n, size, role, sub) => rows.find(r => r.n === n && r.size.startsWith(size) && (role == null || r.role.includes(role)) && (sub == null || r.sub === sub))
export const S = [
  [5, 'desktop', 'admin', null, 'PASS', 'Board "+ Inputs" window and the saved input’s editor on the Board: T2 title kept, kind Event; T3 emptied box stayed empty (hint "Event"), saved as plain Event with no second label; T5 typed and pasted: exactly 40 characters, nothing overlapped; T6 literal text, no markup; T8 new picker offers only Training CSE Meeting Fly with Personal Appointment Duty Event Other, the saved editor took Event to Training (title kept), to LL (no Title box) and back to Event (box "Event", old title not back). Dialog sits above the Board.', ['s5-d-ex-T8']],
  [5, 'phone', 'admin', null, 'PASS', 'Same as desktop at 390 wide with taps: all five cases held at the Board’s new window and at the saved input’s editor; the 40 characters sit in the box with nothing overlapping.', ['s5-p-new-T5a']],
  [6, 'desktop', 'admin', null, 'PASS', 'Shared Event for Ranger and Saber through the Calendar window and the List’s Add form, then retitled in the saved shared window: T2 T3 T5 T6 T8 held; both rows carry one group and one title; the List shows ONE entry; Ranger’s and Saber’s person filters show the same Event rows.', ['s6-d-a-filter-saber']],
  [6, 'desktop', 'member', null, 'PASS', 'Same through a member filer (Ranger, filing for others switched on): all cases held; one shared group, one title. (The member’s own puck cannot be switched off while filing - see extras.)', []],
  [6, 'phone', 'admin', null, 'PASS', 'Same at 390 wide: all cases held, one shared entry, same title for both people.', ['s6-p-a-cal-new-T5a']],
  [6, 'phone', 'member', null, 'PASS', 'Same at 390 wide as a member filer: all cases held, one shared entry.', []],
  [7, 'desktop', 'admin', 'allavail', 'PASS', 'ALL AVAIL through Calendar window, List Add, List pencil and Board Add: T2 T3 T5 T6 T8 held, the placeholder stayed; saving it as LL was refused with "ALL AVAIL can be filed only for Training, Meeting, Appointment, Duty, Event or Other"; back to Event the cleared title did not return.', ['s7-d-a-aa-cal-T8-LL-refused']],
  [7, 'desktop', 'admin', 'all', 'PASS', 'Same for ALL (all four doors); placeholder stayed; LL refused.', ['s7-d-a-all-board-T6']],
  [7, 'desktop', 'ALL AVAIL', 'allavail', 'PASS', 'Member filer: ALL AVAIL through Calendar window, List Add, List pencil (a member has no Board): all cases held, LL refused.', []],
  [7, 'desktop', 'member filer (Ranger) · ALL', 'all', 'PASS', 'Member filer: ALL through the three doors a member has: all cases held, LL refused.', []],
  [7, 'phone', 'admin', 'allavail', 'PASS', 'ALL AVAIL at 390 wide through all four doors: all cases held, LL refused.', ['s7-p-a-aa-board-T5a']],
  [7, 'phone', 'admin', 'all', 'PASS', 'ALL at 390 wide through all four doors: all cases held.', []],
  [7, 'phone', 'ALL AVAIL', 'allavail', 'PASS', 'Member filer at 390 wide, ALL AVAIL: all cases held, LL refused with the sentence on screen.', ['s7-p-m-aa-list-T8-LL-refused']],
  [7, 'phone', 'member filer (Ranger) · ALL', 'all', 'PASS', 'Member filer at 390 wide, ALL: all cases held.', []],
  [9, 'desktop', null, null, 'PASS', 'Title-only draft, then another input clicked behind: "This input has unsaved changes. Open Ranger’s input and lose them?" appeared with Discard and open / Keep editing; Keep editing kept "Unsaved title"; Discard and open showed the other input (Training, Title "Training"); the first input’s saved title unchanged and its box reads "Event".', ['s9-desk-2-question']],
  [9, 'phone', null, null, 'FAIL', 'The question is raised but NOT SEEN: tapping the other input’s card in the day window brings the day window in front of the edit window, so the question and both its buttons are hidden behind it until the day window is closed. After closing it, Keep editing and Discard and open both worked as on desktop (Discard showed the other input, Title "Training", no draft lent; first input unchanged).', ['s9-phone-2-question', 's9-phone-3-other-opened']],
  [10, 'desktop', null, null, 'PASS', 'In all six title editors (Calendar window new and saved, List Add, List pencil, Board + Inputs new, Board saved-input editor): "Must stay here" with equal start and end was refused ("Give the input a start and end that are not the same time"), the form stayed open with the draft, nothing added or changed; corrected times saved with the title; Cancel left the previous saved title.', ['s10-pencil-existing-1-refused']],
  [11, 'desktop', null, null, 'PASS', 'Three Others: titled + remark = "Dental visit" / "Bring letter"; untitled with remark "Dental visit" = "Other" with the remark shown; titled with the same remark = "Dental visit" with the remark shown. Opened day and List agree; every typed remark stays visible.', ['s11-desk-day']],
  [11, 'phone', null, null, 'PASS', 'Same at 390 wide (opened day and List).', ['s11-phone-list']],
  [12, 'desktop', null, null, 'PASS', 'Member filer: shared Event "Team session" retitled "Team review" with a third person added in one save; the first-sorting callsign (Ace) removed: one entry "Team review" of three people; Undo restored Ace with the title, Redo removed him again; after a reload one entry "Ranger +2 · Team review".', ['s12-6-after-reload']],
  [13, 'desktop', null, null, 'PASS', 'Shared Event 30-31 Jul "July session": window dates changed to 31 Jul-1 Aug, retitled "Summer session", a person added: all three rows carry the new dates and name, the month shows one bar over 31 Jul and 1 Aug and none on 30 Jul, remarks "till 1 Aug" without the title, the List holds one entry.', ['s13-2-window-edited']],
  [14, 'desktop', null, null, 'PASS', '"Sports day": dragged on the month (the ghost followed the pointer) from 15 to 16 Jul, hours and remark edited in place on the Board; the week row and the reopened window still say "Sports day"; same after a reload.', ['s14-2-mid-drag']],
  [15, 'desktop', null, null, 'PASS', 'Window draft "Window choice" with the List pencil saving "List choice" behind it: the window shows "Changed while this window was open" naming title with both values; Save before choosing refused ("Choose which to keep first..."); Keep mine saved "Window choice", Take theirs saved "List choice" (two separate inputs).', ['s15-mine-1-notice']],
  [16, 'desktop', null, null, 'PASS', 'Remark changed behind the window: no conflict notice, the window’s Remarks box showed the new remark, Save kept both the title and the remark.', ['s16-1-window-after-remark-change']],
  [17, 'desktop 1440x700', 'admin', null, 'PASS', 'Title, Type, Remarks, Save and Cancel reachable in the window and in the List pencil row (in view or reached by scrolling); typing kept the Title box in view; the save result shown ("Input updated"); Enter in the Title box saved once (no duplicate). Notes: Tab reaches Save and Cancel in the window but NOT in the List pencil row; after Enter a blank "New input" window opens again (see extras).', ['s17-short-a-enter-new']],
  [17, 'desktop 1440x700', 'member', null, 'PASS', 'Same as Ranger on the 700px screen.', []],
  [17, 'phone', 'admin', null, 'PASS', 'At 520px tall (keyboard up): everything reachable by scrolling (Save by scrolling in the window, Title by scrolling in the pencil row); Enter saved once.', ['s17-kb-a-win-typing']],
  [17, 'phone', 'member', null, 'PASS', 'Same as Ranger at 520px tall.', ['s17-kb-m-pen-typing']],
  [22, 'desktop', null, null, 'PASS', 'Personal Inputs cards, week and Board: titled card "Sports day" with small Event, untitled card "Event" with no tag; each opens the right input (Title, Person, Type).', ['s22-d-week-cards']],
  [22, 'phone', null, null, 'PASS', 'Same at 390 wide (week and Board).', ['s22-p-week-cards']],
  [23, 'desktop', null, null, 'PASS', 'Unavailable cards, week and Board: "Overseas visit" with small OD; untitled "OD"; each opens the right input; no Ground Programme row for either OD.', ['s23-d-Board-cards']],
  [23, 'phone', null, null, 'PASS', 'Same at 390 wide.', []],
  [24, 'desktop', null, null, 'FAIL', 'Calendar day, List, week and Board Ground Programme rows hold up (the 40-character title wraps, or is cut by an ellipsis on the day card; the editor shows all 40; no overlaps) BUT on the Board’s Personal Inputs card the 40-character title runs on past its box and over the small Event label and the LATE chip - the kind is not readable there.', ['s24b-desk-Board-card', 's24-d-day', 's24-d-list', 's24b-desk-week-card']],
  [24, 'phone', null, null, 'FAIL', 'Same at 390 wide, worse: on the Board’s Personal Inputs card the title digits print over the Event label and the LATE chip, and a stray digit lands beside the end-time box. The week card and the Ground Programme rows are fine.', ['s24b-phone-Board-card', 's24-p-week', 's24b-phone-week-card']],
  [26, 'desktop', 'admin', null, 'PASS', 'The export downloaded (read through the browser’s download event): header Name, From, To, Start, End, Type, Title, Remarks; rows Event / Sports day, Event / Event and Event / Ops, "A&B" (quoted correctly); every row 8 cells.', ['s26-admin-list']],
  [26, 'desktop', 'member', null, 'PASS', 'Same file as Ranger (all inputs exported): Title beside Type, the quoted title kept in its own cell.', []],
  [27, 'desktop', 'admin', null, 'PASS', 'No Title control on LL, OML, ATT C, Upchit (opened in their window) nor on SANS "+ Commitment"; Events titled LL, ATT B, SANS Availability stayed Events (stored kinds changed by exactly 3 Events), the Medical counts did not move, no SANS offer on that day.', ['s27-admin-sans-editor']],
  [27, 'desktop', 'member', null, 'PASS', 'As Ranger: no Title control on the same leave, medical and Upchit windows; the SANS "+ Commitment" button is disabled for a member (so there is no editor to look at); the three titled Events stayed Events.', []],
  [36, 'desktop', null, null, 'FAIL', 'Next-week peek (7 days after Sunday): the titled Event is drawn "SPORTS DAY" but WITHOUT the small Event label under it (the week itself has it); and after publishing next week’s Wednesday and retitling the input to "Games afternoon", the peek reads GAMES AFTERNOON while View-only Sched (the issued face) still reads SPORTS DAY. (ui-contracts says the peek shows the planned programme only, "no publish/AL state"; the scenario expects the issued name.) Phone: 0 peek nodes at 390 wide (drawn only above 820px) - not walkable there.', ['s36-1-peek-unpublished', 's36-3-peek-published-retitled']],
  [49, 'desktop', null, null, 'PASS', 'Retitled row 38 of 44 in the List: Undo and Redo with it in view left it where it was (same top, same page scroll); with it scrolled far out of view Undo and Redo brought it on screen below the top bar showing the right title; Calendar: Undo of an in-month retitle kept July and the tab (viewing August, Undo returned to July).', ['s49-4-undo-out-of-view']],
]
const out = []
for (const [n, size, role, sub, verdict, said, pics] of S) {
  const base = L(n, size, role, sub)
  if (!base) { console.log('NO ROW for', n, size, role, sub); continue }
  out.push({ n, size: base.size, role: base.role, result: verdict, said, pictures_opened: pics.map(P), pictures_taken_not_opened: (base.pics || []).filter(p => !pics.includes(p.replace(/\.png$/, ''))).length, script_verdict: base.verdict, script_detail: base.say })
}
writeFileSync('docs/handpass/parts/it-A.json', JSON.stringify(out, null, 1))
const cnt = out.reduce((a, r) => (a[r.result] = (a[r.result] || 0) + 1, a), {})
console.log(JSON.stringify(cnt), out.length)
console.log(out.filter(r => r.result !== r.script_verdict).map(r => `${r.n} ${r.size} ${r.role}: script said ${r.script_verdict}, I say ${r.result}`).join('\n'))
