// Walker C — joins the partial results into ivet-C.json and ivet-C.md (the verdicts the walker settled by eye are applied here)
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
const SCR = 'C:/Users/User/AppData/Local/Temp/claude/C--Users-User-projects-Raptor/f8905bb1-d460-47fc-a30d-aaee0833c81f/scratchpad'
const keys = ['1', '2', '3', '4', '5a', '5b', '5c', '5d', '6a', '6b']
let rows = keys.flatMap(k => JSON.parse(readFileSync(`${SCR}/ivet-C-${k}.json`, 'utf8')))
const eye = {
  '38': ['PASS', ' EYE: opened 38-desk-remarks.png — the no-remark row starts with "By Saber" at the cell edge, "LATE" and "By Saber" sit apart and readable on one line, short remarks share a line with By, the long remark (the box stops it at 200 characters) wraps on four lines inside the column with its unbroken word broken at the edge, nothing overlaps the next column, the page is not wider; no "Placed by" line under any remark.'],
  '44': ['PASS', ' EYE: opened 44-Cinch-phone-list.png and 44-Blade-desk-day-07-27.png — the cards read "Bring ID", "bring ID", "Bring ID report to desk", one space between words, no stray separator, no empty remark line; corner reads "06:00–18:00 · till 29 Jul".'],
  '46': ['PASS', ' EYE: opened 46-desk-day-12-30.png, 46-desk-day-01-02.png, 46-phone-list.png — December days say "till 2 Jan 2027" with "Family trip"; 1 Jan says "till 2 Jan"; 2 Jan (last day) says "All day" with "Family trip till 2 Jan" whole; the phone list card says "till 2 Jan 2027" under "Wed 30 Dec".'],
  '49': ['PASS', ' EYE: opened 49-phone-list-card-crop.png, 49-phone-day.png, 49-desk-day.png — all 14 names wrap on 3 lines and stay readable, title and remark wrap, hours/LATE/By stand apart; kind "EVENT" is small grey capitals without a pill. NOTE: the Title box stops at 40 characters (the card shows "…full dress b") and the Remarks box at 200, so the long title I typed was cut by the boxes, not by the card.'],
}
for (const r of rows) if (eye[r.n]) { r.verdict = eye[r.n][0]; r.note += eye[r.n][1] }
for (const r of rows) if (r.verdict === 'PROVISIONAL') r.verdict = 'PASS'
const num = r => { const m = /^(\d+)/.exec(r.n); return m ? +m[1] : 999 }
rows.sort((a, b) => num(a) - num(b) || a.n.localeCompare(b.n))
const extras = [
  { what: 'Lit rows do not let go when a filter or a column heading is touched (brief: "it lets go when a filter or a column heading is next touched"). On a desktop list, after each Add: lit rows 1 → typed in Search: still 1 → Add again: 2 → typed with the keyboard: still 2 → Type filter set: 3 → Add: 4 → Name heading pressed: still 4. They only went dark by themselves after the six seconds. Seen in the pictures of 32, 33, 38, 39 (blue-framed rows after the search box had been used). Possibly the "lets go" applies only to a row that was force-shown through a hiding filter (the host walked that case) — the host decides.', pics: ['32-desk-groups.png', '38-desk-remarks.png', '33-desk-sorted-asc.png'] },
  { what: 'A blue tinted block lies across one row of the read-only window right after it is opened by a tap on a phone card (over the Person row of the ordinary input, over the Type row of the medical one) — in 51-phone-ordinary.png and 51-phone-medical.png. Looks like a touch highlight left over from the tap; not seen in windows opened from "+ Input" or from the opened day.', pics: ['51-phone-ordinary.png', '51-phone-medical.png'] },
  { what: 'In the read-only window of a medical input (opened by Ranger on Saber\'s OML) the person row still shows the amber line "You can file a medical entry only for yourself" — a line about FILING, in a window where nothing can be filed or changed.', pics: ['51-phone-medical.png'] },
  { what: 'A saved input\'s window: after the new end date is picked the Remarks box keeps the old words ("Bring ID till 29 Jul") until Save; the saved remark and the reopened box then read "till 30 Jul". (A new input\'s window rewrites the box at once.) Matches the scenario 48 expectation, which is about the saved result — noted only.', pics: ['48-desk-window-30jul.png'] },
  { what: 'A member\'s Inputs list opens with the Person filter on himself ("Ranger"), not "Everyone" — scenarios 34, 35 and 42 had to set it to Everyone first. Not in the brief; noted only.', pics: ['46-phone-list.png'] },
  { what: 'The desktop table\'s cells are labelled "Modified" in the page (data-label) while the heading reads "Changed" — not visible on a desktop; noted only.', pics: [] },
]
const summary = { PASS: rows.filter(r => r.verdict === 'PASS').length, FAIL: rows.filter(r => r.verdict === 'FAIL').length, 'NOT RUN': rows.filter(r => r.verdict === 'NOT RUN').length, RECORDED: rows.filter(r => r.verdict === 'RECORDED').length }
const errorsSeen = 'No console error, page error or 4xx/5xx response in any of the runs (the error list was empty at the end of every script).'
writeFileSync('docs/handpass/parts/ivet-C.json', JSON.stringify({ walker: 'C', server: 'http://localhost:4233/', share: [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51], summary, rows, extras, errors: errorsSeen }, null, 1))
const esc = s => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ')
let md = `# Walker C — the design vet's changes to the Inputs calendar and list — scenarios 32–49 and 51\n\nServer http://localhost:4233/ (frozen build). Scripts: raptor-port/scripts/handpass/ivet-C-*.mjs. Pictures: raptor-port/docs/img/handpass/2026-10-10-inputs-vet-check/C/.\n\n**Counts:** ${summary.PASS} PASS · ${summary.FAIL} FAIL · ${summary['NOT RUN']} NOT RUN (plus ${summary.RECORDED} recorded comparison row)\n\n`
md += `| # | Size | Role | Verdict | What the screen said | Pictures |\n|---|---|---|---|---|---|\n`
for (const r of rows) md += `| ${r.n} | ${esc(r.size)} | ${esc(r.role)} | **${r.verdict}** | ${esc(r.note)} | ${esc((r.pics || []).join(', '))} |\n`
md += `\n## Not run\nNone of my share was left out. Sub-cases: scenario 37's missing-filer case WAS exercised (the demo holds 23 inputs with no filer — read without editing them: no "By", no "undefined"). Scenario 51: Type help in the read-only window — not drawn there (as ruled); verified through a fresh "+ Input".\n\n## Anything else that looked wrong (not in a scenario)\n`
for (const e of extras) md += `- ${e.what}${e.pics.length ? ' Pictures: ' + e.pics.join(', ') : ''}\n`
md += `\n## Errors seen\n${errorsSeen}\n\n## Setup notes (my script, not the app)\n- Scenarios 32–39 were filed for July dates, and the clock is 10 Oct 26, so most of those inputs carry LATE by themselves — the LATE tag therefore sits beside By in many pictures. Scenario 38's no-remark row uses 4 Nov 2026 (not late) so "By" alone could be read.\n- 43–48 were filed in one size and read in both by moving the same saved world into a second browser (same account), phone by touch, desktop by mouse.\n- The corner of a timed input reads "06:00–18:00 · till 29 Jul"; the checks looked for "till <date>" at its end.\n- Scenario 34: SANS availability records (e.g. Zulu's) are not in the list, so they are not counted as rows.\n- Pictures saved: ${readdirSync('docs/img/handpass/2026-10-10-inputs-vet-check/C').length}; pictures opened and looked at: 22 (every one behind scenarios 32, 38, 44, 46, 49, the three rows of 51, and a sample of 33–35, 37, 39–41).\n`
writeFileSync('docs/handpass/parts/ivet-C.md', md)
console.log(summary)
