import * as L from './ivet-C-lib.mjs'
const { page, ctx } = await L.open(L.DESK, 'ad', 'a', false, { fresh: false })
console.log(await page.evaluate(() => Object.values(window.PEOPLE).map(p => p.cs + (p.archived ? '(arch)' : '') + (p.special ? '(sp)' : '')).join(', ')))
await L.toList(page, false)
const r = await L.fileInput(page, { type: 'Meeting', person: 'Ranger', from: '2026-07-27', rmk: 'probe' }, false)
console.log(JSON.stringify(r))
await L.shot(page, 'probe-1')
const st = await ctx.storageState()
console.log('storage keys', st.origins.map(o => o.localStorage.length + ' keys'))
const ctx2 = await L.browser.newContext({ viewport: L.DESK, storageState: st })
const p2 = await ctx2.newPage()
await p2.goto(L.BASE)
await p2.waitForTimeout(1000)
console.log('login visible', await p2.locator('#luser').count(), 'week', await p2.locator('#vWeek .day').count())
if (await p2.locator('#luser').count()) await L.signInAs(p2, 'us', 'us')
console.log('inputs in 2nd', await p2.evaluate(() => window.INPUTS.length), await p2.evaluate(() => window.INPUTS.filter(r => r.remarks === 'probe').length))
await L.browser.close()
console.log(L.errs)
