import * as L from './ivet-C-lib.mjs'
const PNG = L.SCR + '/c51-doc.png'
const { page } = await L.open(L.PHONE, 'ad', 'a', true, { fresh: true })
await L.toList(page, true)
const had = await L.ids(page)
await L.plus(page, true)
await page.selectOption('#inpEditType', 'OML'); await page.selectOption('#inpEditPerson', await L.csId(page, 'Saber'))
await L.pick(page, '2026-08-10', true)
await page.locator(`${L.WIN} input[type=file]`).setInputFiles(PNG)
await page.waitForTimeout(500)
console.log('chips', await page.locator(`${L.WIN} .docchip`).count(), await page.locator(`${L.WIN} .docchip`).allInnerTexts())
await L.shot(page, 'dbg-doc-attached')
await page.locator('#inpEditSave').tap(); await page.waitForTimeout(700)
console.log('docconf', await page.locator('[data-testid="docconf"]').count(), 'toast', await L.toast(page))
await L.shot(page, 'dbg-doc-after-save')
console.log(JSON.stringify(await page.evaluate(had => window.INPUTS.filter(r => !had.includes(r.iid)), had)))
await L.browser.close()
