import * as K from './stk2-S-lib.mjs'
import * as S from './stk2-M-alib.mjs'
const { L, W, H } = K
const DI = 3
const { browser, p, errors } = await H.world({ who: 'a', phone: false })
await L.go(p, 'editsched'); await K.sleep(500)
await W.boardOn(p, DI); await K.sleep(400)
const waves0 = await p.evaluate(i => window.DAYS[i].waves.map(w => w.label), DI)
console.log('waves before', waves0)
// + Wave -> Flying wave
const wb = p.locator(`#schedBoard [data-wvadd="${DI}"]`).first()
await wb.evaluate(e => e.scrollIntoView({ block: 'center' })); await wb.click(); await K.sleep(350)
await p.locator('.wavemenu [data-wmkind=""]').first().click(); await K.sleep(700)
const waves1 = await p.evaluate(i => window.DAYS[i].waves.map(w => w.label), DI)
const gi = waves1.length - 1
console.log('new wave', gi, waves1[gi])
const boxes = await p.evaluate(g => [...document.querySelectorAll(`#schedBoard [data-bfld^="ff:3.${g}."]`)].map(e => e.dataset.bfld + '=' + e.value), gi)
console.log('boxes', boxes)
const ctl = await p.evaluate(g => { const b = document.querySelector(`#schedBoard [data-lcx="3.${g}.0.0"]`); const c = b && b.closest('.lctl'); return c ? [...c.querySelectorAll('button')].map(x => x.innerText.trim() + '|' + [...x.attributes].map(a => a.name + '=' + a.value).join(' ')) : null }, gi)
console.log('line buttons', ctl)
// type NO take-off on the blank line? "NO take-off" = leave take-off empty
const to0 = await p.evaluate(g => (document.querySelector(`#schedBoard [data-bfld="ff:3.${g}.0.to"]`) || {}).value, gi)
console.log('take-off box', JSON.stringify(to0))
// + In-time / Rally
await S.addItBtn(p, DI, gi)
const it0 = await S.intimes(p, DI, gi)
console.log('after + In-time/Rally', JSON.stringify(it0))
const issues = async () => { await H.boardOpenFold(p); const b = await H.readBoard(p); return { head: b.head, lines: b.lines.map(l => l.text), other: b.other } }
const fbOf = () => p.evaluate(g => [...document.querySelectorAll('#schedBoard [data-reporting-feedback]')].filter(e => e.offsetParent !== null).map(e => (e.getAttribute('data-warnkey') || '') + ' :: ' + e.innerText.replace(/\s+/g, ' ').trim()), gi)
const hdr = () => p.evaluate(g => [...document.querySelectorAll('#schedBoard .sb-go-h')].map(e => e.innerText.replace(/\s+/g, ' ').trim()), gi)
const waveIssues = r => r.lines.filter(t => /reporting line|recognised clock|clock/i.test(t))
// (a)
await S.setItLine(p, DI, gi, 0, '8h00 IN TIME')
const a_fb = await fbOf(), a_is = await issues(), a_hdr = await hdr(), a_it = await S.intimes(p, DI, gi)
const a_app = (await S.warnsOf(p, DI)).filter(x => /REPORT|clock/i.test(x.code + x.msg)).map(x => `${x.sev}/${x.code}: ${x.msg}`)
const pa = await K.pic(p, 'S4a-unreadable-clock')
console.log('(a)', JSON.stringify({ a_it, a_fb, a_is: waveIssues(a_is), a_hdr: a_hdr[gi], a_app }))
// (b)
await S.setItLine(p, DI, gi, 0, '0800 IN TIME')
const b_fb = await fbOf(), b_is = await issues(), b_hdr = await hdr(), b_it = await S.intimes(p, DI, gi)
const b_app = (await S.warnsOf(p, DI)).filter(x => /REPORT|clock/i.test(x.code + x.msg)).map(x => `${x.sev}/${x.code}: ${x.msg}`)
const pb = await K.pic(p, 'S4b-readable-clock')
console.log('(b)', JSON.stringify({ b_it, b_fb, b_is: waveIssues(b_is), b_hdr: b_hdr[gi], b_app }))
// (c) put 8h00 back, then remove the wave's only line with its ✕ (the line's own delete button)
await S.setItLine(p, DI, gi, 0, '8h00 IN TIME')
const c0_fb = await fbOf()
const delBtn = p.locator(`#schedBoard [data-lcx="3.${gi}.0.0"]`).first().locator('xpath=ancestor::*[contains(@class,"lctl")][1]').locator('button.del, button:has-text("✕")').first()
const delAttrs = await delBtn.evaluate(e => [...e.attributes].map(a => a.name + '=' + a.value).join(' ')).catch(() => 'no delete button found')
console.log('delete button', delAttrs)
await delBtn.evaluate(e => e.scrollIntoView({ block: 'center' })); await delBtn.click(); await K.sleep(700)
const dlg = await p.evaluate(() => { const d = [...document.querySelectorAll('.airpop')].filter(e => e.getBoundingClientRect().width > 0).pop(); return d ? d.innerText.replace(/\s+/g, ' ').slice(0, 200) : null })
console.log('dialog after ✕', dlg)
const nlines = await p.evaluate(g => document.querySelectorAll(`#schedBoard [data-bfld^="ff:3.${g}."]`).length, gi)
const c_fb = await fbOf(), c_is = await issues(), c_hdr = await hdr()
const c_app = (await S.warnsOf(p, DI)).filter(x => /REPORT|clock/i.test(x.code + x.msg)).map(x => `${x.sev}/${x.code}/${x.key}: ${x.msg}`)
const c_it = await S.intimes(p, DI, gi)
const pc = await K.pic(p, 'S4c-no-line-left')
console.log('(c)', JSON.stringify({ nlines, c_it, c0_fb, c_fb, c_is: waveIssues(c_is), c_hdr: c_hdr[gi], c_app }))
// (d) + Line again
const gl = p.locator(`#schedBoard [data-gline="${DI}.${gi}"]`).first()
await gl.evaluate(e => e.scrollIntoView({ block: 'center' })); await gl.click(); await K.sleep(700)
const d_fb = await fbOf(), d_is = await issues(), d_hdr = await hdr()
const d_app = (await S.warnsOf(p, DI)).filter(x => /REPORT|clock/i.test(x.code + x.msg)).map(x => `${x.sev}/${x.code}/${x.key}: ${x.msg}`)
const pd = await K.pic(p, 'S4d-line-again')
console.log('(d)', JSON.stringify({ d_fb, d_is: waveIssues(d_is), d_hdr: d_hdr[gi], d_app }))
const nan = await p.evaluate(() => /NaN/.test(document.body.innerText))
const MSG = /reporting line 1 has no recognised clock\. Check the time\./
const cnt = (a) => a.filter(t => MSG.test(t)).length
K.note('S-4', 'a', 'Board Thursday 16 Jul: + Wave (Flying wave), take-off left empty, + In-time / Rally, line text replaced with "8h00 IN TIME", box left', `lines ${JSON.stringify(a_it)}; line under the reporting box: ${JSON.stringify(a_fb)}; day issues list (reporting/clock lines): ${JSON.stringify(waveIssues(a_is))}; app warnings: ${JSON.stringify(a_app)}; wave header "${a_hdr[gi]}"`, (a_fb.some(t => MSG.test(t)) && cnt(a_is.lines) >= 1) ? 'PASS' : 'FAIL', [pa])
K.note('S-4', 'b', 'replaced with "0800 IN TIME"', `lines ${JSON.stringify(b_it)}; under box: ${JSON.stringify(b_fb)}; issues (reporting/clock): ${JSON.stringify(waveIssues(b_is))}; app warnings ${JSON.stringify(b_app)}; wave header "${b_hdr[gi]}"`, (b_fb.length === 0 || !b_fb.some(t => /recognised|Check the time/i.test(t))) && waveIssues(b_is).length === 0 && /08:00/.test(b_hdr[gi]) ? 'PASS' : 'FAIL', [pb])
K.note('S-4', 'c', 'put "8h00 IN TIME" back, removed the wave\'s only line with its ✕', `delete button ${delAttrs}; dialog "${dlg}"; formation boxes left in wave: ${nlines}; reporting lines ${JSON.stringify(c_it)}; under box: ${JSON.stringify(c_fb)}; issues (reporting/clock): ${JSON.stringify(waveIssues(c_is))}; app warnings ${JSON.stringify(c_app)}; header "${c_hdr[gi]}"`, cnt(c_is.lines) >= 1 ? 'PASS' : 'FAIL', [pc])
K.note('S-4', 'd', '+ Line again on that wave', `under box: ${JSON.stringify(d_fb)}; issues (reporting/clock): ${JSON.stringify(waveIssues(d_is))}; copies of the message in the issues list: ${cnt(d_is.lines)}; app warnings ${JSON.stringify(d_app)}; header "${d_hdr[gi]}"; NaN on page: ${nan}`, cnt(d_is.lines) === 1 ? 'PASS' : 'FAIL', [pd])
console.log('errors', K.errList(errors))
K.flush()
await browser.close()
