/* walker B — a first look to learn the screen (not a walk step): Tuesday published flagged, a hide, every count */
import { L, W, world, reloadAs, openList, readList, tapLine, lineIx, pucks, flagged, warnsOf, head, pic } from './wh-lib.mjs'
import { changesList, alPanel } from './p6-lib.mjs'
const { browser, p, errors } = await world()
const TUE = 1
await L.go(p, 'editsched'); await openList(p, '#eWeek', TUE)
const l0 = await readList(p, '#eWeek', TUE)
console.log('LIST0', JSON.stringify(l0, null, 1))
console.log('WARNS', JSON.stringify(await warnsOf(p, TUE)))
console.log('HEAD0', JSON.stringify(await head(p, TUE)))
console.log('SIGN', JSON.stringify(await W.signDay(p, TUE)))
console.log('PUB', JSON.stringify(await W.publishDay(p, TUE)))
console.log('HEAD1', JSON.stringify(await head(p, TUE)))
await openList(p, '#eWeek', TUE)
const l1 = await readList(p, '#eWeek', TUE)
console.log('LIST1', JSON.stringify(l1.lines.map(x => [x.ix, x.hid, x.struck, x.btn, x.btnTop, x.text])))
const ix = lineIx(l1, /long work day/i)
console.log('ix', ix, await tapLine(p, '#eWeek', TUE, ix))
console.log('HEAD2', JSON.stringify(await head(p, TUE)))
const l2 = await readList(p, '#eWeek', TUE)
console.log('LIST2', l2.bar, JSON.stringify(l2.lines.map(x => [x.ix, x.hid, x.struck, x.btn, x.btnTop, x.text])))
console.log('WOLF', JSON.stringify(await pucks(p, `#eWeek .day[data-day="${TUE}"]`, 'wolf')))
await pic(p, 'probe-pending')
console.log('CHG', JSON.stringify(await changesList(L, p, TUE), null, 1))
console.log('ALP', JSON.stringify(await alPanel(p)))
console.log('ALPHTML', await p.evaluate(() => { const a = document.querySelector('#alPanel'); return a ? a.outerHTML.slice(0, 3000) : null }))
/* the changes window markup */
const c = p.locator(`#eWeek .day[data-day="${TUE}"] .dpend`).first(); await c.click(); await L.sleep(600)
console.log('CHGHTML', await p.evaluate(() => { const w = document.querySelector('.chgwin:not([hidden])'); return w ? w.outerHTML.slice(0, 5000) : null }))
await pic(p, 'probe-chgwin')
await p.locator('.chgwin:not([hidden]) .win-x').first().click().catch(() => {})
/* day head html */
console.log('HEADHTML', await p.evaluate(i => document.querySelector(`#eWeek .day[data-day="${i}"] .day-head`).outerHTML.slice(0, 3000), TUE))
/* the plan menu */
await W.showDay(p, TUE)
await p.locator(`#eWeek [data-planmenu="${TUE}"]:visible`).first().click(); await L.sleep(400)
console.log('PLANMENU', await p.evaluate(() => [...document.querySelectorAll('[data-planpv]')].map(e => [e.dataset.planpv, e.innerText.replace(/\s+/g, ' ')])))
await pic(p, 'probe-planmenu')
const pv = p.locator('[data-planpv]:visible').first(); await pv.click(); await L.sleep(600)
console.log('PVHEAD', await p.evaluate(i => { const d = document.querySelector(`#eWeek .day[data-day="${i}"]`); return { cls: d.className, bar: (d.querySelector('.dprev-bar') || {}).innerText, head: d.querySelector('.day-head').innerText.replace(/\s+/g, ' ') } }, TUE))
await openList(p, '#eWeek', TUE)
const l3 = await readList(p, '#eWeek', TUE)
console.log('PVLIST', l3.bar, JSON.stringify(l3.lines.map(x => [x.ix, x.hid, x.struck, x.btn, x.text])))
await pic(p, 'probe-look-orig')
/* ⓘ */
const info = p.locator(`#eWeek .day[data-day="${TUE}"] [data-dayinfo]:visible`).first()
console.log('INFOBTN', await info.count())
if (await info.count()) { await info.click(); await L.sleep(400); console.log('DAYPOP', await p.evaluate(() => { const b = document.querySelector('#dayPopBody'); return b ? b.innerHTML.slice(0, 4000) : null })); await pic(p, 'probe-daypop'); await p.locator('#dayPopClose').click().catch(() => {}) }
await p.locator(`[data-golive="${TUE}"]:visible`).first().click().catch(e => console.log('nogolive', String(e).slice(0, 100))); await L.sleep(400)
/* the member */
await reloadAs(p, 'm'); await L.sleep(400)
await openList(p, '#vWeek', TUE)
const lm = await readList(p, '#vWeek', TUE)
console.log('MEMBER', lm.bar, JSON.stringify(lm.lines.map(x => [x.ix, x.hid, x.struck, x.btn, x.text])))
console.log('MWOLF', JSON.stringify(await pucks(p, `#vWeek .day[data-day="${TUE}"]`, 'wolf')))
console.log('MHEAD', await p.evaluate(i => document.querySelector(`#vWeek .day[data-day="${i}"] .day-head`).outerHTML.slice(0, 2500), TUE))
await pic(p, 'probe-member')
await p.locator('#insightBtn').click().catch(e => console.log('noinsight', String(e).slice(0, 100))); await L.sleep(400)
console.log('INSIGHT', await p.evaluate(() => { const b = document.querySelector('#insightBody'); return b ? b.innerText.slice(0, 3000) : null }))
await pic(p, 'probe-insights')
console.log('ERRORS', JSON.stringify(errors))
await browser.close()
