import { open, go, box, OUT } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'ad' })
await go(page, 'editsched')
const t = '#eWeek .day[data-day="0"] [data-daytplopen="0"], [data-daytplopen="0"]'
console.log('tpl btn', JSON.stringify(await box(page, '[data-daytplopen="0"]')), await page.locator('[data-daytplopen]').count())
await page.click('[data-daytplopen="0"]'); await page.waitForTimeout(400)
console.log('menu', JSON.stringify(await box(page, '.wavemenu')), await page.$eval('.wavemenu', e => e.innerText.replace(/\s+/g, ' ')))
await page.screenshot({ path: OUT + '/j14-4-daytpl-menu.png' })
await page.click('.wavemenu [data-daytpledit]'); await page.waitForTimeout(400)
console.log('daytpl modal open', await page.locator('#daytplModal:not([hidden])').count())
await page.click('#daytplClose'); await page.waitForTimeout(300)
// board
console.log('sb-open', JSON.stringify(await box(page, '.sb-open[data-sbday="0"]')))
await page.click('.sb-open[data-sbday="0"]'); await page.waitForTimeout(900)
console.log('SBDAY', await page.evaluate(() => window.SBDAY))
for (const s of ['[data-dwadd="0"]', '[data-wvadd="0"]', '#sbBoard']) console.log(s, JSON.stringify(await box(page, s).catch(() => null)))
await page.screenshot({ path: OUT + '/j14-5-board.png' })
await page.locator('[data-dwadd="0"]').scrollIntoViewIfNeeded()
await page.click('[data-dwadd="0"]'); await page.waitForTimeout(400)
console.log('block menu', JSON.stringify(await box(page, '.wavemenu')), await page.$eval('.wavemenu', e => e.innerText.replace(/\s+/g, ' ')))
await page.screenshot({ path: OUT + '/j14-6-blockmenu.png' })
await page.click('.wavemenu [data-blkedit]'); await page.waitForTimeout(400)
console.log('duty modal open', await page.locator('#tplModal:not([hidden])').count())
await page.screenshot({ path: OUT + '/j14-7-duty-from-board.png' })
await page.click('#tplClose'); await page.waitForTimeout(300)
await page.locator('[data-wvadd="0"]').scrollIntoViewIfNeeded()
await page.click('[data-wvadd="0"]'); await page.waitForTimeout(400)
console.log('wave menu', JSON.stringify(await box(page, '.wavemenu')), await page.$eval('.wavemenu', e => e.innerText.replace(/\s+/g, ' ')))
await page.screenshot({ path: OUT + '/j14-8-wavemenu.png' })
await page.click('.wavemenu [data-wvedit]'); await page.waitForTimeout(400)
console.log('wave modal open', await page.locator('#waveTplModal:not([hidden])').count())
console.log(errs)
await browser.close()
