import { open, go, box, OUT } from './lib.mjs'
import { readFileSync } from 'node:fs'
const { browser, ctx, page, errs } = await open({ who: 'ad' })
await go(page, 'editsched')
for (const s of ['#exportSched', '#exportPdf', '#page-editsched .filters']) console.log(s, JSON.stringify(await box(page, s)))
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 5000 }), page.click('#exportSched')])
const p = OUT + '/sched.csv'; await dl.saveAs(p)
console.log('download', dl.suggestedFilename(), readFileSync(p, 'utf8').split('\n').slice(0, 3))
await page.waitForTimeout(200)
console.log('toast', await page.$eval('#toastEl', e => e.textContent).catch(() => null))
await page.screenshot({ path: OUT + '/j15-1-csv-toast.png' })
await page.waitForTimeout(3500)
// PDF: capture the iframe html
const t0 = Date.now()
await page.click('#exportPdf')
console.log('click returned after', Date.now() - t0, 'ms')
await page.waitForTimeout(800)
console.log('toast', await page.$eval('#toastEl', e => e.textContent).catch(() => null))
const html = await page.evaluate(() => { const f = [...document.querySelectorAll('iframe')].pop(); return f ? f.srcdoc : null })
console.log('iframe html len', html && html.length)
await page.screenshot({ path: OUT + '/j15-2-pdf-toast.png' })
if (html) {
  const p2 = await ctx.newPage(); await p2.setViewportSize({ width: 794, height: 1123 }); await p2.setContent(html); await p2.screenshot({ path: OUT + '/j15-3-pdf-render.png' }); await p2.pdf({ path: OUT + '/sched.pdf', format: 'A4' }).catch(e => console.log('pdf err', e.message.slice(0, 80)))
}
// inputs export
await go(page, 'inputs')
const [dl2] = await Promise.all([page.waitForEvent('download', { timeout: 5000 }), page.click('#inExport')])
console.log('inputs download', dl2.suggestedFilename())
await go(page, 'quals')
const [dl3] = await Promise.all([page.waitForEvent('download', { timeout: 5000 }), page.click('#qExport')])
console.log('quals download', dl3.suggestedFilename())
// admin data
await go(page, 'admin')
await page.click('.adm-rail .adm-cat:has-text("Data")'); await page.waitForTimeout(400)
console.log('data', await page.$eval('#admData', e => e.innerText.replace(/\s+/g, ' ')))
console.log('controls', await page.$$eval('#admData input, #admData select, #admData button', a => a.map(e => e.tagName + '#' + e.id + (e.tagName === 'SELECT' ? '[' + [...e.options].map(o => o.value + '=' + o.text).join(',') + ']' : '') + ' ' + (e.textContent || '').trim())))
for (const s of ['#admData', '#admWipe', '#admLog', '#admWipeMode', '#admLogMode']) console.log(s, JSON.stringify(await box(page, s)))
await page.screenshot({ path: OUT + '/j15-4-data.png' })
console.log(errs)
await browser.close()
