import { open, go, box, OUT } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'ad' })
await go(page, 'editsched')
await page.click('.sb-open[data-sbday="1"]'); await page.waitForTimeout(900)
console.log('sbweek', await page.$$eval('#sbDays [data-sbweek]', a => a.map(e => e.dataset.sbweek + ':' + e.textContent)));
for (const s of ['#sbCal', '#sbPrevDay', '#sbNextDay', '#sbDays [data-sbtab="2"]', '#sbTpl', '#sbDone']) console.log(s, JSON.stringify(await box(page, s)))
await page.screenshot({ path: OUT + '/j6b-1-board.png' })
await page.click('#sbDays [data-sbtab="2"]'); await page.waitForTimeout(700)
console.log('SBDAY', await page.evaluate(() => window.SBDAY))
console.log('SBDAY', await page.evaluate(() => window.SBDAY))
await page.click('#sbTpl'); await page.waitForTimeout(400)
console.log('menu', await page.$eval('.wavemenu', e => e.innerText.replace(/\s+/g, ' ').slice(0, 120)))
await page.keyboard.press('Escape')
await page.click('#sbDone'); await page.waitForTimeout(500)
console.log('SBDAY after done', await page.evaluate(() => window.SBDAY))
console.log(errs); await browser.close()
