import { open, go, box, OUT } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'us' })
await go(page, 'inputs')
await page.waitForSelector('#inAdd')
console.log('types', await page.$$eval('#inType option, #inType optgroup', a => a.map(o => (o.tagName === 'OPTGROUP' ? '## ' + o.label : o.value + '=' + o.textContent))))
console.log('type default', await page.$eval('#inType', s => s.value), 'person', await page.$eval('#inPersonFixed', e => e.textContent))
console.log('cal mon', await page.$eval('#inCal .rc-mon', e => e.textContent), 'rows', await page.$$eval('#inBody tr', a => a.length))
for (const s of ['.title', '#inCalBtn', '#inMedBtn', '.inbar', '#inPersonFixed', '#inCal', '#inDates', '#inSpan', '#inType', '#inRemarks', '#inAdd', '#inExport', '#intbl', '#inFPerson', '#inRangeBtn']) console.log(s, JSON.stringify(await box(page, s)))
await page.screenshot({ path: OUT + '/j7-1-form.png' })
console.log(errs)
await browser.close()
