import { open, go, box, OUT } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'us' })
await go(page, 'inputs')
await page.waitForSelector('#inAdd')
await page.click('#inCal [data-cal="2026-07-13"]'); await page.waitForTimeout(150)
await page.click('#inCal [data-cal="2026-07-15"]'); await page.waitForTimeout(150)
await page.selectOption('#inType', 'ATT C'); await page.waitForTimeout(200)
console.log('docfield', await page.locator('.docfield').count(), JSON.stringify(await box(page, '.inbar .docbtn')))
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64')
await page.setInputFiles('.inbar .docfield input[type=file]', { name: 'MC-Ranger.png', mimeType: 'image/png', buffer: png })
await page.waitForTimeout(300)
console.log('chips', await page.$$eval('.inbar .docchip', a => a.map(e => e.textContent)))
console.log('remarks', await page.$eval('#inRemarks', e => e.value))
await page.screenshot({ path: OUT + '/j7-5-med-filled.png' })
await page.click('#inAdd'); await page.waitForTimeout(700)
console.log('ask', await page.locator('[data-testid="docconf"]').count(), 'toast', await page.$eval('#toastEl', e => e.textContent).catch(() => null))
console.log('rows', await page.$$eval('#inBody tr', a => a.map(r => r.innerText.replace(/\s+/g, ' ').slice(0, 120))))
await page.click('#inMedBtn'); await page.waitForTimeout(600)
console.log('med', await page.$eval('#medView', e => e.innerText.replace(/\s+/g, ' ').slice(0, 600)))
console.log('cards', await page.$$eval('#medView .medcard', a => a.map(e => e.dataset.medcard + ':' + e.innerText.replace(/\s+/g, ' '))))
await page.screenshot({ path: OUT + '/j7-6-medview.png' })
const mine = page.locator('#medView .medcard', { hasText: 'Ranger' }).first()
console.log('mine box', JSON.stringify(await mine.boundingBox()))
await mine.click(); await page.waitForTimeout(600)
console.log('docview', await page.$$eval('.docview, [class*=docv], [role=dialog]', a => a.map(e => e.className + ' :: ' + e.innerText.replace(/\s+/g, ' ').slice(0, 300))))
await page.screenshot({ path: OUT + '/j7-7-docview.png' })
console.log(errs)
await browser.close()
