import { open, go, box, OUT } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'us' })
await go(page, 'inputs')
await page.click('#inCal [data-cal="2026-07-15"]')
console.log('dates', await page.$eval('#inDates', e => e.textContent), 'rmk', await page.$eval('#inRemarks', e => e.value))
await page.selectOption('#inType', 'Appointment')
await page.fill('#inStartT', '10:00'); await page.fill('#inEndT', '12:00'); await page.fill('#inRemarks', 'Dental appt')
await page.screenshot({ path: OUT + '/j7g-1.png', clip: { x: 0, y: 115, width: 560, height: 420 } })
await page.screenshot({ path: OUT + '/j7g-2.png', clip: { x: 520, y: 115, width: 640, height: 480 } })
await page.click('#inAdd'); await page.waitForTimeout(500)
console.log('toast', await page.$eval('#toastEl', e => e.textContent).catch(() => null))
console.log('new row', await page.$eval('#inBody tr.innew', r => r.innerText.replace(/\s+/g, ' ')), JSON.stringify(await box(page, '#inBody tr.innew')))
await page.screenshot({ path: OUT + '/j7g-3.png', clip: { x: 0, y: 330, width: 800, height: 600 > 570 ? 570 : 600 } })
await go(page, 'viewsched')
const loc = page.locator('#vWeek .day[data-day="2"] .pl-row', { hasText: 'Dental appt' }).first()
console.log('row count', await loc.count())
await loc.scrollIntoViewIfNeeded(); await page.waitForTimeout(400)
const b = await loc.boundingBox(); console.log('row box', JSON.stringify(b), 'text', (await loc.innerText()).replace(/\s+/g, ' '))
console.log('week scrollLeft', await page.$eval('#vWeek', e => e.scrollLeft), 'winY', await page.evaluate(() => scrollY))
await page.screenshot({ path: OUT + '/j7g-4.png' })
console.log(errs); await browser.close()
