import { start } from './lib.mjs'
const { browser, page, errors, shot, box, ballBox } = await start('ad')
const B = async s => JSON.stringify(await box(s))
// course menu
await page.click('#courseMenuBtn'); await page.waitForTimeout(200)
await shot('p2-coursemenu', { x: 0, y: 50, w: 640, h: 480 })
console.log('courseMenuPanel', await B('#courseMenuPanel'), await B('#addCourse'), await B('#delCourse'))
await page.keyboard.press('Escape'); await page.waitForTimeout(150)
await page.click('#sylMenuBtn'); await page.waitForTimeout(200)
await shot('p2-sylmenu', { x: 160, y: 50, w: 640, h: 480 })
console.log('sylMenuPanel', await B('#sylMenuPanel'), await B('#arrangeBtn'), await B('#delSyl'))
await page.keyboard.press('Escape'); await page.waitForTimeout(150)
await page.click('#fileMenuBtn'); await page.waitForTimeout(200)
await shot('p2-filemenu', { x: 400, y: 50, w: 640, h: 480 })
console.log('fileMenuPanel', await B('#fileMenuPanel'), await B('#importFileBtn'), await B('#exportBtn'))
await page.keyboard.press('Escape'); await page.waitForTimeout(150)
// show all
await page.click('#showAllBtn'); await page.waitForTimeout(400)
await shot('p2-showall')
console.log('showAll', await B('#showAllPanel'), await B('#saSearch'), await B('#showAllPanel .sarow .sedit'))
await page.click('#saClose'); await page.waitForTimeout(200)
// details mode
await page.click('#detailsBtn'); await page.waitForTimeout(300)
const st = await ballBox('ST-01'); await page.mouse.move(st.x + st.width/2, st.y + st.height/2); await page.waitForTimeout(400)
await shot('p2-details')
console.log('detailsHint', await B('#detailsHint'), await page.evaluate(() => { const b = [...document.querySelectorAll('#page-tracker .bubble, #page-tracker [id*=ubble], .detailbubble, #detailBubble')].map(e => (e.id||e.className) + '|' + e.textContent.slice(0,120)); return b }))
await page.click('#detailsHintOff'); await page.waitForTimeout(200)
// search
await page.fill('#hSearch', 'BFM'); await page.waitForTimeout(400)
await shot('p2-search')
console.log('search', await B('#hSearchList'), await B('#hSearchStat'), await page.textContent('#hSearchStat'), await page.evaluate(() => [...document.querySelectorAll('#hSearchList .findrow')].map(e => e.textContent).slice(0, 8)))
await page.keyboard.press('Enter'); await page.waitForTimeout(500)
await shot('p2-search2')
console.log('ringed', await page.evaluate(() => document.querySelectorAll('#flowSvg .ball .searchring, #flowSvg circle.search, #flowSvg [class*=search]').length))
// crew
console.log('crew B marks', await page.evaluate(() => { const c = window.__coreForTests; return c ? Object.keys(c) .slice(0,80) : 'no core' }))
console.log('errors', errors)
await browser.close()
