import { start } from './lib.mjs'
const { browser, page, errors, shot, box, ballBox, clickBall } = await start('ad')
const B = async s => JSON.stringify(await box(s))
console.log('ST-01', JSON.stringify(await ballBox('ST-01')))
await clickBall('ST-01'); await page.waitForSelector('#pop'); await page.waitForTimeout(300)
console.log('pop', await B('#pop'), await page.textContent('#popTitle'))
for (const t of ['Not done', 'DCO', 'DPCO', 'Marginal', 'N.A.', 'Close']) console.log(t, await B(`#pop .opts button:has-text("${t}")`))
console.log('doneDate', await B('#popDoneDate'), await page.inputValue('#popDoneDate'), 'fail+', await B('#popFailPlus'), await B('#popFailDate'), await B('#popEditInfo'), await B('#popInfo'))
await shot('p3-pop')
await page.click('#pop .opts button:has-text("DCO")'); await page.waitForTimeout(500)
await shot('p3-after-dco')
console.log('after DCO: overall', await page.textContent('.c-overall .big'), 'topundo title', await page.getAttribute('#trUndoBtn', 'title'))
// ST-02 fail twice then NA
await clickBall('ST-02'); await page.waitForSelector('#pop'); await page.waitForTimeout(300)
await page.click('#popFailPlus'); await page.waitForTimeout(250)
await page.click('#popFailPlus'); await page.waitForTimeout(250)
console.log('failCount', await page.textContent('#failCount'), await B('#popFailDates'), await page.textContent('#popFailDates'))
await shot('p3-fails')
await page.click('#pop .opts button:has-text("N.A.")'); await page.waitForTimeout(400)
await clickBall('ST-02'); await page.waitForSelector('#pop'); await page.waitForTimeout(300)
await page.click('#popFailPlus'); await page.waitForTimeout(300)
console.log('NA refuse', await B('#popFailWarn'), await page.textContent('#popFailWarn').catch(()=>null), await page.textContent('#failCount'), 'hint', await page.textContent('#arrhint'))
await shot('p3-na-refuse')
await page.keyboard.press('Escape'); await page.waitForTimeout(300)
// future date refusal
await clickBall('ST-03'); await page.waitForSelector('#pop'); await page.waitForTimeout(300)
await page.fill('#popDoneDate', '2026-10-05'); await page.waitForTimeout(200)
await page.click('#pop .opts button:has-text("DCO")'); await page.waitForTimeout(300)
console.log('future refuse', await B('#popDoneWarn'), await page.textContent('#popDoneWarn').catch(()=>null), 'pop still?', await page.locator('#pop').count())
await shot('p3-future')
await page.keyboard.press('Escape'); await page.waitForTimeout(300)
await shot('p3-final')
console.log('side fails', await B('#failsCard'), await page.textContent('#failsCard'))
console.log('errors', errors)
await browser.close()
