import { open, go, box, txt, shot } from './lib.mjs'
const { browser, page, errs } = await open({ who: 'us' })
console.log('page', await page.evaluate(() => window.CURPAGE), 'wk', await txt(page, 'button.wk.on:visible'))
const days = page.locator('#vWeek .day')
console.log('days', await days.count())
for (let i = 0; i < 7; i++) {
  const d = days.nth(i)
  console.log(i, (await d.locator('.dh, .dhd, header').first().innerText().catch(() => '?')).replace(/\s+/g, ' ').slice(0, 60), 'bane pucks', await d.locator('.puck[data-person="bane"]').count())
}
console.log('tue unav:', await txt(page, '#vWeek .day >> nth=1 >> .sec-unav', 400))
await shot(page, 'r1a-view-before')
await go(page, 'inputs')
console.log('rows', await page.$$eval('#inBody tr', a => a.map(r => r.innerText.replace(/\s+/g, ' ').slice(0, 100))))
console.log('types', await page.$$eval('#inType option', a => a.map(o => o.value).join(',')))
await page.click('#inCal [data-cal="2026-07-14"]'); await page.waitForTimeout(150)
console.log('span', await txt(page, '#inSpan'), 'dates', await txt(page, '#inDates'))
await page.selectOption('#inType', 'LL'); await page.waitForTimeout(200)
await shot(page, 'r1a-form')
await page.click('#inAdd'); await page.waitForTimeout(800)
console.log('toast', await txt(page, '#toastEl'))
console.log('rows after', await page.$$eval('#inBody tr', a => a.map(r => r.innerText.replace(/\s+/g, ' ').slice(0, 100))))
await shot(page, 'r1a-inputs-after')
console.log(errs)
await browser.close()
