import { browser, fresh, go, shot, box, sign, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
const signs = () => page.$$eval('#eWeek select[data-sign][data-signday="0"]', a => a.map(s => s.options[s.selectedIndex].text))
const drag = async (pid, fill) => {
  const src = page.locator(`#eRoster .rpuck[data-person="${pid}"]`).first(), cell = page.locator(`#eWeek [data-fill="${fill}"]`).first()
  const sb = await src.boundingBox(), cb = await cell.boundingBox()
  await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down(); await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
  await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 12 }); await page.mouse.up(); await page.waitForTimeout(800)
}
await sign(page, 0); console.log('draft signed', await signs())
await drag('beams', 'a:0.0.+'); console.log('draft after edit', await signs(), await page.evaluate(() => document.getElementById('toastEl')?.textContent))
await sign(page, 0); await page.click('button[data-beak="0"]'); await page.waitForTimeout(900)
await drag('boosh', 'a:0.8.+')
await sign(page, 0); console.log('pub pending signed', await signs(), await page.$eval('#eWeek .day[data-day="0"] .dhver', e => e.innerText))
await drag('nomad' , 'a:0.9.+').catch(e => console.log('drag err', e.message))
console.log('pub after 2nd edit', await signs(), await page.$eval('#eWeek .day[data-day="0"] .dhver', e => e.innerText), await page.$eval('#eWeek .day[data-day="0"] .dpend', e => e.innerText))
console.log('toast', await page.evaluate(() => document.getElementById('toastEl')?.textContent))
// view-only page: what does it show for Monday
await go(page, 'viewsched')
console.log('view head', await page.evaluate(() => document.querySelector('#vWeek .day[data-day="0"] .day-head')?.innerText.replace(/\s+/g, ' ')))
console.log('view has Havoc?', await page.evaluate(() => document.querySelector('#vWeek .day[data-day="0"]')?.innerText.includes('Havoc')))
// member
const m = await fresh('us')
console.log('member nav', await m.$$eval('.nav a', a => a.filter(x => x.offsetWidth).map(x => x.innerText)))
console.log('member undo visible', await box(m, '#undoBtn'), 'hist', await box(m, '#histBtn'))
await go(m, 'viewsched')
console.log('member planmenu on view', await m.locator('[data-planmenu]:visible').count(), 'dver', await m.locator('select.dver:visible').count())
console.log(errors)
await browser.close()
