import { browser, fresh, go, shot, box, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
await page.click('#eWeek [data-sbday="0"]:visible')
await page.waitForSelector('#schedBoard'); await page.waitForTimeout(800)
const toast = () => page.evaluate(() => { const t = document.getElementById('toastEl'); return t && t.style.opacity !== '0' ? t.textContent.trim() : '' })
const menu = () => page.evaluate(() => [...document.querySelectorAll('.wavemenu')].filter(e => e.offsetWidth).map(e => { const b = e.getBoundingClientRect(); return `@${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)} :: ` + [...e.querySelectorAll('button, h5, .wm-note')].map(x => `${x.tagName}[${[...x.attributes].filter(a=>a.name.startsWith('data-')).map(a=>a.name+'='+a.value).join(' ')}]"${x.innerText.replace(/\s+/g,' ').slice(0,50)}"`).join(' | ') }))
// scroll + Wave into view
const wv = page.locator('#schedBoard [data-wvadd="0"]')
await wv.evaluate(e => e.scrollIntoView({ block: 'center' })); await page.waitForTimeout(300)
console.log('scrollY', await page.evaluate(() => window.scrollY), 'wvadd', await box(page, wv), 'gline', await box(page, '#schedBoard [data-gline="0.0"]'))
await shot(page, 'p4-waves')
await wv.click(); await page.waitForTimeout(500)
console.log('wave menu', await menu())
await shot(page, 'p4-wavemenu')
await page.keyboard.press('Escape'); await page.waitForTimeout(300)
console.log('menu after esc', await menu())
// + Line
const lines0 = await page.locator('#schedBoard [data-ldel^="0.0."]').count()
await page.locator('#schedBoard [data-gline="0.0"]').click(); await page.waitForTimeout(600)
console.log('lines', lines0, '->', await page.locator('#schedBoard [data-ldel^="0.0."]').count(), 'toast', await toast())
await shot(page, 'p4-afterline')
// + Block duty
const blk = page.locator('#schedBoard [data-dwadd="0"]')
await blk.evaluate(e => e.scrollIntoView({ block: 'center' })); await page.waitForTimeout(300)
await blk.click(); await page.waitForTimeout(500)
console.log('block menu', await menu())
await shot(page, 'p4-blockmenu')
console.log(errors)
await browser.close()
