import { browser, fresh, go, shot, box, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
await page.click('#eWeek [data-sbday="0"]:visible')
await page.waitForSelector('#schedBoard'); await page.waitForTimeout(800)
const sc = await page.evaluate(() => { const b = document.querySelector('[data-wvadd="0"]'); let e = b; const out = []; while (e) { const s = getComputedStyle(e); if (/(auto|scroll)/.test(s.overflowY) && e.scrollHeight > e.clientHeight) out.push(`${e.tagName}#${e.id}.${String(e.className).slice(0,30)} sh=${e.scrollHeight} ch=${e.clientHeight}`); e = e.parentElement } return out })
console.log('scrollers', sc)
console.log(await page.$$eval('#schedBoard [data-fill]', a => a.slice(0, 8).map(e => { const b = e.getBoundingClientRect(); return `${e.tagName}.${e.className} fill=${e.dataset.fill} "${e.innerText.replace(/\s+/g,' ').slice(0,30)}" @${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}` })))
console.log(await page.$$eval('#sbRoster .rpuck[data-person]', a => a.slice(0, 4).map(e => { const b = e.getBoundingClientRect(); return `${e.className} p=${e.dataset.person} drag=${e.dataset.drag} "${e.innerText.replace(/\s+/g,' ')}" @${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}` })))
// drag Comet (beams) onto SODB people cell
const src = page.locator('#sbRoster .rpuck[data-person="beams"]').first()
const cell = page.locator('#schedBoard [data-fill]').first()
const fill = await cell.getAttribute('data-fill')
const sb = await src.boundingBox(), cb = await cell.boundingBox()
await shot(page, 'p5-before')
await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down()
await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
await page.mouse.move((sb.x + cb.x) / 2, (sb.y + cb.y) / 2, { steps: 8 })
await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 8 })
await shot(page, 'p5-mid')
await page.mouse.up(); await page.waitForTimeout(700)
console.log('after', await page.locator(`#schedBoard [data-fill="${fill}"]`).innerText().catch(()=>'gone'))
const sodb = await page.evaluate(() => { const r = [...document.querySelectorAll('#schedBoard input')].find(i => i.value === 'SODB'); const row = r && r.closest('.sb-row, .sb-arow, [class*=row]'); return row ? row.innerText.replace(/\s+/g, ' ') + ' || ' + row.className : 'no row' })
console.log('sodb row', sodb)
await shot(page, 'p5-after')
console.log('toast', await page.evaluate(() => document.getElementById('toastEl')?.textContent))
console.log(errors)
await browser.close()
