import { browser, fresh, go, shot, box, sign, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
const toast = () => page.evaluate(() => { const t = document.getElementById('toastEl'); return t && t.style.opacity !== '0' ? t.textContent.trim() : '' })
const head = () => page.evaluate(() => { const s = document.querySelector('#eWeek .day[data-day="0"]'); const q = x => s.querySelector(x); return { head: q('.day-head')?.innerText.replace(/\s+/g,' '), dpend: q('.dpend')?.innerText, verchip: q('.verchip')?.outerHTML.slice(0,200), dhver: q('.dhver')?.innerText, beak: q('[data-beak="0"]')?.innerText, alpub: q('[data-alpub="0"]')?.outerHTML.slice(0,250), unpub: q('[data-unpub="0"]')?.innerText, signs: [...s.querySelectorAll('select[data-sign]')].map(x => x.options[x.selectedIndex].text), amend: document.querySelector('.amendbar, #amendBar, [class*=amend]')?.innerText?.replace(/\s+/g,' ').slice(0,200) } })
await sign(page, 0)
await page.click('button[data-beak="0"]'); await page.waitForTimeout(900)
console.log('toast', await toast())
console.log('PUB', await head())
await shot(page, 'p6-published')
// drag Comet onto Monday SODB on the week
const src = page.locator('#eRoster .rpuck[data-person="beams"]').first()
const cell = page.locator('#eWeek [data-fill="a:0.0.+"]').first()
console.log('src', await box(page, src), 'cell', await box(page, cell))
const sb = await src.boundingBox(), cb = await cell.boundingBox()
await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down()
await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 12 })
await page.mouse.up(); await page.waitForTimeout(900)
console.log('toast', await toast())
console.log('EDITED', await head())
console.log('marks', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="0"] [data-alp], #eWeek .day[data-day="0"] [data-aln]')].map(e => { const b = e.getBoundingClientRect(); return `${e.tagName}.${String(e.className).slice(0,40)} alp=${e.dataset.alp} aln=${e.dataset.aln} "${e.innerText.replace(/\s+/g,' ').slice(0,30)}" @${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}` })))
await shot(page, 'p6-edited')
await sign(page, 0)
console.log('RESIGNED', await head())
await shot(page, 'p6-resigned')
await page.click('button[data-alpub="0"]'); await page.waitForTimeout(900)
console.log('toast', await toast())
console.log('AL1', await head())
console.log('issued marks', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="0"] [data-alc]')].slice(0,6).map(e => { const b = e.getBoundingClientRect(); return `${e.tagName}.${String(e.className).slice(0,40)} alc=${e.dataset.alc} "${e.innerText.replace(/\s+/g,' ').slice(0,30)}" @${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}` })))
await shot(page, 'p6-al1')
await page.click('button[data-unpub="0"]'); await page.waitForTimeout(900)
console.log('toast', await toast())
console.log('after unpub1', await head())
await shot(page, 'p6-unpub')
console.log(errors)
await browser.close()
