import { browser, fresh, go, shot, box, sign, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
const toast = () => page.evaluate(() => { const t = document.getElementById('toastEl'); return t && t.style.opacity !== '0' ? t.textContent.trim() : '' })
const head = () => page.evaluate(() => { const s = document.querySelector('#eWeek .day[data-day="0"]'); const q = x => s.querySelector(x); return q('.day-head')?.innerText.replace(/\s+/g,' ') })
const menu = () => page.evaluate(() => [...document.querySelectorAll('.wavemenu')].filter(e => e.offsetWidth).map(e => { const b = e.getBoundingClientRect(); return `@${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)} :: ` + [...e.querySelectorAll('button, h5, .wm-note, .wm-hdr')].map(x => { const bb = x.getBoundingClientRect(); return `${x.tagName}.${x.className}[${[...x.attributes].filter(a=>a.name.startsWith('data-')).map(a=>a.name+'='+a.value).join(' ')}]"${x.innerText.replace(/\s+/g,' ').slice(0,90)}"@${Math.round(bb.x)},${Math.round(bb.y)} ${Math.round(bb.width)}x${Math.round(bb.height)}` }).join('\n   ') }))
const closeMenu = async () => { await page.mouse.click(700, 180); await page.waitForTimeout(300) }
const drag = async (pid, fill) => {
  const src = page.locator(`#eRoster .rpuck[data-person="${pid}"]`).first(), cell = page.locator(`#eWeek [data-fill="${fill}"]`).first()
  const sb = await src.boundingBox(), cb = await cell.boundingBox()
  await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down(); await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
  await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 12 }); await page.mouse.up(); await page.waitForTimeout(800)
}
// DRAFT day menu first
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
console.log('DRAFT MENU', await menu()); await shot(page, 'p7-draftmenu')
await closeMenu(); console.log('menu closed?', (await menu()).length)
// publish Monday
await sign(page, 0); await page.click('button[data-beak="0"]'); await page.waitForTimeout(900)
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
console.log('PUB MENU', await menu()); await shot(page, 'p7-pubmenu')
await page.click('.wavemenu [data-plandup]'); await page.waitForTimeout(800)
console.log('toast', await toast()); console.log('head', await head())
await shot(page, 'p7-afterdup')
await drag('beams', 'a:0.0.+')
console.log('after drag head', await head())
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
console.log('MENU 2 plans', await menu()); await shot(page, 'p7-menu2')
// switch to the other plan
const other = page.locator('.wavemenu [data-plansel]').first()
console.log('other', await other.innerText())
await other.click(); await page.waitForTimeout(800)
console.log('toast', await toast()); console.log('head', await head())
await shot(page, 'p7-switched')
// switch back to alt
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
console.log('MENU 3', await menu())
await page.locator('.wavemenu [data-plansel]').first().click(); await page.waitForTimeout(800)
console.log('toast', await toast()); console.log('head', await head())
console.log('pending marks', await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="0"] [data-alp]')].map(e => e.innerText.replace(/\s+/g,' '))))
await shot(page, 'p7-back')
// Look at ORIG
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
await page.locator('.wavemenu [data-planpv]').first().click(); await page.waitForTimeout(800)
console.log('preview head', await head()); await shot(page, 'p7-preview')
console.log('banner', await page.evaluate(() => document.querySelector('#eWeek .day[data-day="0"] .dprev-bar, #eWeek .day[data-day="0"] [class*=prev]')?.innerText))
// manage
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
await page.locator('.wavemenu [data-plangolive]').first().click(); await page.waitForTimeout(600)
await page.click('#eWeek [data-planmenu="0"]'); await page.waitForTimeout(500)
await page.locator('.wavemenu [data-planmanage]').first().click(); await page.waitForTimeout(800)
await shot(page, 'p7-manage')
console.log('modal', await page.evaluate(() => [...document.querySelectorAll('.modal, [role=dialog], .mbg, .modalbg, .ovl')].filter(e=>e.offsetWidth).map(e => e.className + ' :: ' + e.innerText.replace(/\s+/g,' ').slice(0,400))))
console.log(errors)
await browser.close()
