import { browser, fresh, go, shot, box, sign, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
const toast = () => page.evaluate(() => { const t = document.getElementById('toastEl'); return t && t.style.opacity !== '0' ? t.textContent.trim() : '' })
const st = () => page.evaluate(() => ({ undo: document.querySelector('#undoBtn').disabled, undoT: document.querySelector('#undoBtn').title, redo: document.querySelector('#redoBtn').disabled, redoT: document.querySelector('#redoBtn').title, sodb: document.querySelector('#eWeek [data-fill="a:0.0.+"]')?.innerText.replace(/\s+/g,' '), chip: document.querySelector('#eWeek .day[data-day="0"] .dpend')?.outerHTML.slice(0,160), hist: document.querySelector('#histBtn').outerHTML.slice(0, 300) }))
console.log('start', await st())
const drag = async (pid, fill) => {
  const src = page.locator(`#eRoster .rpuck[data-person="${pid}"]`).first(), cell = page.locator(`#eWeek [data-fill="${fill}"]`).first()
  const sb = await src.boundingBox(), cb = await cell.boundingBox()
  await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down(); await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
  await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 12 }); await page.mouse.up(); await page.waitForTimeout(800)
}
await drag('beams', 'a:0.0.+')
console.log('after drag', await st(), await toast())
await shot(page, 'p8-dragged')
await page.click('#undoBtn'); await page.waitForTimeout(700)
console.log('after undo', await st(), await toast())
await shot(page, 'p8-undone')
await page.click('#redoBtn'); await page.waitForTimeout(700)
console.log('after redo', await st(), await toast())
await shot(page, 'p8-redone')
// edit a time on Monday too
const tk = await page.evaluate(() => [...document.querySelectorAll('#eWeek .day[data-day="0"] [data-txt]')].map(e => e.dataset.txt).slice(0, 10))
console.log('txt keys', tk)
await page.click('#histBtn'); await page.waitForTimeout(800)
await shot(page, 'p8-histwin')
console.log('win', await page.evaluate(() => { const w = document.querySelector('.chgwin'); if (!w) return 'none'; const b = w.getBoundingClientRect(); return `@${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)} hidden=${w.hidden}\n` + [...w.querySelectorAll('button, .win-ttl, .cw-hint, .cw-gh, .cw-l, .win-tab')].map(x => { const bb = x.getBoundingClientRect(); return `${x.tagName}.${x.className}[${[...x.attributes].filter(a=>a.name.startsWith('data-')).map(a=>a.name+'='+a.value).join(' ')}] "${x.innerText.replace(/\s+/g,' ').slice(0,90)}" @${Math.round(bb.x)},${Math.round(bb.y)} ${Math.round(bb.width)}x${Math.round(bb.height)}` }).join('\n') }))
console.log('dots', await page.locator('#eWeek [data-histdot]').count())
console.log(errors)
await browser.close()
