import { browser, fresh, go, shot, box, sign, errors } from './lib.mjs'
const page = await fresh()
await go(page, 'editsched')
const drag = async (pid, fill) => {
  const src = page.locator(`#eRoster .rpuck[data-person="${pid}"]`).first(), cell = page.locator(`#eWeek [data-fill="${fill}"]`).first()
  const sb = await src.boundingBox(), cb = await cell.boundingBox()
  await page.mouse.move(sb.x + 5, sb.y + 5); await page.mouse.down(); await page.mouse.move(sb.x + 15, sb.y + 15, { steps: 3 })
  await page.mouse.move(cb.x + cb.width / 2, cb.y + cb.height / 2, { steps: 12 }); await page.mouse.up(); await page.waitForTimeout(800)
}
const dump = () => page.evaluate(() => { const w = document.querySelector('.chgwin'); if (!w || w.hidden) return 'none'; return [...w.querySelectorAll('.cw-body *')].filter(x => x.children.length === 0 || x.matches('button, .cw-gh')).filter(x=>x.offsetWidth).slice(0, 30).map(x => { const bb = x.getBoundingClientRect(); return `${x.tagName}.${x.className}[${[...x.attributes].filter(a=>a.name.startsWith('data-')).map(a=>a.name+'='+a.value).join(' ')}] "${x.innerText.replace(/\s+/g,' ').slice(0,90)}" @${Math.round(bb.x)},${Math.round(bb.y)} ${Math.round(bb.width)}x${Math.round(bb.height)}` }).join('\n') })
await drag('beams', 'a:0.0.+')
// edit a time: MET + NOTAM end time on Monday (ap:0.1.end)
const el = page.locator('#eWeek [data-txt="ap:0.1.end"]').first()
console.log('time cell', await box(page, el), await el.innerText())
await el.click(); await page.keyboard.press('Control+A'); await page.keyboard.type('08:45', { delay: 10 }); await el.evaluate(e => e.blur()); await page.waitForTimeout(700)
console.log('time now', await el.innerText())
// Tuesday: drag Havoc onto SODB Tue
await drag('boosh', 'a:1.0.+')
await page.waitForTimeout(3000)
// day chip
await page.click('#eWeek .day[data-day="0"] .dpend'); await page.waitForTimeout(800)
await shot(page, 'p9-chip-open')
console.log('chip opened ->', await page.evaluate(() => { const w = document.querySelector('.chgwin'); return w && !w.hidden ? [...w.querySelectorAll('.win-tab.on, .cw-day.on, .cw-g-btn.on')].map(x => x.innerText.replace(/\s+/g,' ')).join(' | ') : 'none' }))
console.log(await dump())
await page.click('.chgwin .cw-g-btn:has-text("Who")'); await page.waitForTimeout(500)
await shot(page, 'p9-who')
console.log('WHO\n' + await dump())
await page.click('.chgwin .cw-g-btn:has-text("Item")'); await page.waitForTimeout(500)
await page.click('.chgwin .cw-day:has-text("Week")'); await page.waitForTimeout(500)
console.log('WEEK ITEM\n' + await dump())
await shot(page, 'p9-week-item')
// tap the Tuesday line
const tueLine = page.locator('.chgwin button.cw-l').filter({ hasText: /Tue|SODB|Havoc/ }).last()
console.log('tap line', await tueLine.innerText().catch(() => 'none'))
await page.evaluate(() => window.scrollTo(0, 0))
const sx0 = await page.evaluate(() => document.querySelector('#eWeek')?.scrollLeft)
await tueLine.click(); await page.waitForTimeout(1000)
console.log('after tap: week scrollLeft', sx0, '->', await page.evaluate(() => document.querySelector('#eWeek')?.scrollLeft), 'winY', await page.evaluate(() => window.scrollY))
console.log('bubble', await page.evaluate(() => { const b = document.querySelector('.histbub'); return b && b.offsetWidth ? b.innerText.replace(/\s+/g,' ') + ' @' + JSON.stringify(b.getBoundingClientRect()) : 'none' }))
console.log('flash/focus', await page.evaluate(() => [...document.querySelectorAll('.lift-land, .hl-focus, .flash, [class*=flash], .cw-focus')].map(e => e.className + ' ' + e.innerText?.slice(0, 20))))
await shot(page, 'p9-tapped')
// dots count, then close
console.log('dots', await page.locator('[data-histdot]').count())
await page.click('.chgwin .win-x'); await page.waitForTimeout(400)
console.log('dots after close', await page.locator('[data-histdot]').count())
console.log(errors)
await browser.close()
