// THE DAY VIEW — what one person's box on one date shows, what it costs and
// who it removes ([ARCH-STACK] step 4, phase 1).
//
// A box is no longer "one code". Since step 4 a person/date can hold several
// records at once — filed absences (derived from the Inputs page, never stored
// on the war), the war's own requests, OIL credits and replaced-bid notices —
// and the owner settled how they read together (19–20 Sep 26):
//   docs/superpowers/specs/2026-09-19-arch-stack-4-clash-catalogue.md
//     ("Main-code priority — AGREED", owner answers)
//   docs/superpowers/specs/2026-09-20-arch-stack-4-clash-check.md
//     (B1–B9, H1–H6, answers A–D — this one wins where they differ)
//
// ONE pure function, `dayView`, turns the list into the box. Every screen and
// every figure reads it, so the box, the balance and the manning count can
// never disagree about the same day. It never looks at the calendar (weekends,
// the 15-day run) — that stays with `charge.ts`, which reads `charges` and
// `annualFull` off this.
//
// Time model (the app's one split, `inputs.ts` HALF_AM/HALF_PM): minutes of
// the day, inclusive windows. Morning = 0–720 (00:00–12:00), afternoon =
// 721–1439 (12:01–23:59). An end at 12:00 and a start at 12:01 do NOT overlap.

import { LEAVE_TYPES, type CounterName, type Portion } from './codes'

export type Win = readonly [number, number]
export const AM: Win = [0, 720]
export const PM: Win = [721, 1439]
export const FULL: Win = [0, 1439]

export type RequestState = 'pending' | 'acknowledged' | 'refused'

/** One thing on a person's day. `id` is the Input's iid for an absence and
 *  the war record's own id otherwise — the tap list acts on it. */
export interface Contrib {
  id: string
  kind: 'absence' | 'request' | 'credit' | 'notice'
  /** Leave War notation type, no portion marks: LL, OL, OIL, ATTC, HL, OML,
   *  ATTB, CSE, OD, FO, HO. A notice carries the REPLACED bid's code. */
  code: string
  /** The part of this date it takes — for a credit worked in several
   *  stretches, the envelope from first start to last end (what it shows as). */
  win: Win
  /** credit only: the separate work stretches, when there are several. Every
   *  overlap test reads these, so leave in a GAP between two stretches is not a
   *  clash (Fable inspection #2, 20 Sep 26). */
  wins?: readonly Win[]
  /** request only */
  state?: RequestState
  /** absence only: approved on the war (the Input carries `lw`) */
  lw?: boolean
  /** credit only: generated by the OIL pass (the war may not edit it) */
  auto?: boolean
  /** credit only: how many days it is worth, when not the code's own worth */
  days?: number
  /** credit only: why it was earned */
  note?: string
  /** credit only, and HAND-TYPED only: on whose say-so (owner, 20 Sep 26).
   *  Recorded is not the same as visible — a field nobody can read is the
   *  shape of the bug where a man was charged for leave his row no longer
   *  showed. */
  givenBy?: string
  /** a closed-bidding move landed it here from this date (the dotted mark) */
  movedFrom?: string
  /** an overnight record's tail from the day before: it counts for clashes
   *  here but is displayed and charged on its own date (clash-check H6) */
  spill?: boolean
}

const LEAVE = new Map<string, CounterName | null>(LEAVE_TYPES.map(t => [t.type, t.counter]))
const SICK = new Set(['ATTC', 'HL', 'OML'])
const AWAY_DUTY = new Set(['OD', 'CSE'])
const CREDIT = new Set(['FO', 'HO'])
export const isLeaveCode = (code: string) => LEAVE.has(code)
export const isSickCode = (code: string) => SICK.has(code)
export const isAwayDutyCode = (code: string) => AWAY_DUTY.has(code)
export const isCreditCode = (code: string) => CREDIT.has(code)
const isAnnual = (code: string) => code === 'LL' || code === 'OL'

/* Two windows clash only when they share time: an end and a start at the same
   minute (LL 08:00–10:00, OL 10:00–11:00) sit back to back and do NOT clash —
   the owner's own example had a gap, and back-to-back is the natural reading
   (20 Sep 26 overnight call). The halves still never meet: morning ends 12:00
   (720), afternoon starts 12:01 (721). */
export const overlaps = (a: Win, b: Win) => a[0] < b[1] && b[0] < a[1]
/** every stretch a contribution really takes */
export const winsOf = (c: Contrib): readonly Win[] => c.wins ?? [c.win]
export const touchesAM = (w: Win) => w[0] <= AM[1]
export const touchesPM = (w: Win) => w[1] >= PM[0]
/** minutes of `w` inside `half` (inclusive windows) */
const minutesIn = (w: Win, half: Win) => Math.max(0, Math.min(w[1], half[1]) - Math.max(w[0], half[0]) + 1)

/** The notation portion a window reads as: a window touching both halves is a
 *  full day (today's round-OUT rule, `sync.ts rowPortion` — never
 *  under-report an absence). */
export function portionOf(w: Win): Portion {
  const a = touchesAM(w), p = touchesPM(w)
  return a && p ? 'full' : a ? 'am' : 'pm'
}

/** The main-code ladder (owner, 19 Sep 26 — "leave over sick"). Lower wins. */
export function levelOf(c: Contrib): number {
  if (c.kind === 'notice') return 99            // never the main code
  if (c.kind === 'request') return c.state === 'refused' ? 7 : 6
  if (c.kind === 'credit') return 3
  if (LEAVE.has(c.code)) return 1
  if (SICK.has(c.code)) return 2
  if (AWAY_DUTY.has(c.code)) return 4
  if (c.code === 'ATTB') return 5
  return 8                                        // an unknown code: shown last, removes nobody
}

/** Order for the box and the tap list: the ladder, then a full day over a
 *  half, then the earlier start (morning before afternoon), then the id. */
export function compareContrib(a: Contrib, b: Contrib): number {
  return levelOf(a) - levelOf(b)
    || (portionOf(b.win) === 'full' ? 1 : 0) - (portionOf(a.win) === 'full' ? 1 : 0)
    || a.win[0] - b.win[0]
    || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0)
}

/** A pair the owner's rules say cannot stand together on the same time.
 *  Everything else sits side by side as grey `+n`. A refused request is
 *  history and clashes with nothing; a notice is not a time claim. */
export function forbiddenPair(a: Contrib, b: Contrib): boolean {
  if (a.kind === 'notice' || b.kind === 'notice') return false
  if (a.state === 'refused' || b.state === 'refused') return false
  if (!winsOf(a).some(x => winsOf(b).some(y => overlaps(x, y)))) return false
  /* An AWARD clashes with nothing (owner, 20 Sep 26). A hand-typed credit says
     a man is OWED a day; it does not say where he was, so it cannot contradict
     a day off and must not amber it. The app's OWN credit (`auto`) still
     flags — that one is read off the published schedule and does say he was at
     work. This sits before the pair table so it exempts BOTH clash rows a
     credit appears in (leave and medical), not just the leave one. */
  if ((a.kind === 'credit' && !a.auto) || (b.kind === 'credit' && !b.auto)) return false
  const leaveLike = (c: Contrib) => LEAVE.has(c.code) && (c.kind === 'absence' || c.kind === 'request')
  const sick = (c: Contrib) => c.kind === 'absence' && SICK.has(c.code)
  const work = (c: Contrib) => c.kind === 'credit'
  const pairs: Array<[(c: Contrib) => boolean, (c: Contrib) => boolean]> = [
    [leaveLike, leaveLike],   // two leaves on the same time (§25, H3 overruled → real times)
    [leaveLike, sick],        // sick cuts leave; leave over sick is refused (§26.1)
    [leaveLike, work],        // leave on recorded work — FLAGS the day; since
                              // 20 Sep 26 it no longer bars a write (barsWrite)
    [sick, work],             // ATT C/HL/OML on a worked time (owner Q6)
  ]
  return pairs.some(([p, q]) => (p(a) && q(b)) || (p(b) && q(a)))
}

/** Does this pair BAR a write, as opposed to merely flagging the day?
 *
 *  Every forbidden pair raises the amber `!` — that is `forbiddenPair`'s job
 *  and it is unchanged. This is the narrower question each write door asks
 *  before refusing, and since the owner's ruling of 20 Sep 26 the answer for
 *  RECORDED WORK is no: work and an absence may sit on the same hours, the day
 *  is flagged, and a human resolves it by removing one side. That holds
 *  wherever the leave arrives from — the Inputs page form, a bid on the grid,
 *  an approval, or a move — because the owner's whole reason was that the same
 *  two facts must not be kept or lost depending on which screen was used.
 *
 *  It SETS ASIDE clash-check B5's "a bid made after the publish that overlaps
 *  published work is refused at the bid door": put to the owner on 20 Sep 26
 *  with that consequence spelled out, and overruled.
 *
 *  What still bars is what B7 always barred: two leaves on the same time, and
 *  leave over a medical. */
export const barsWrite = (a: Contrib, b: Contrib) =>
  a.kind !== 'credit' && b.kind !== 'credit' && forbiddenPair(a, b)

export interface Charge {
  counter: CounterName
  amount: number
  code: string
  id: string
  /** which half, when it is half a day */
  half?: 'am' | 'pm'
}

/** personId → date → the day view. */
export type Views = Record<string, Record<string, DayView>>

export interface DayView {
  /** the main record, or null for an empty day */
  main: Contrib | null
  /** every record, main first, in ladder order (spill tails excluded) */
  all: Contrib[]
  /** the stored notation of the main code: `LL`, `*LL` (morning), `LL*` */
  code: string | null
  /** the main code's colour state: an absence or credit reads approved */
  state: 'pending' | 'acknowledged' | 'approved' | 'refused' | null
  /** the corner mark: '!' when an admin must look, '+n' for more records, '' */
  mark: string
  amber: boolean
  /** the forbidden pairs found (the clash strip) */
  conflicts: Array<[Contrib, Contrib]>
  /** what this day costs, per balance — a half is charged ONCE however many
   *  leave records share it (owner, 20 Sep 26), by the one covering more of it */
  charges: Charge[]
  /** the fraction of this day the person is away from the manning picture */
  away: number
  /** at work but off the flying programme — an OIL credit the SCHEDULE earned.
   *  A hand-typed award never sets this (owner, 20 Sep 26). */
  duty: boolean
  /** OIL earned by the credits on this day: FO a whole day, HO a half — or
   *  the quantity a grant names, which may be more (owner, 20 Sep 26) */
  earnsOil: number
  /** both halves covered by LL/OL and no other leave type on the day — what
   *  continues the pilots' 15-day run (owner Q13, clash-check H4) */
  annualFull: boolean
}

const EMPTY: DayView = Object.freeze({
  main: null, all: [], code: null, state: null, mark: '', amber: false,
  conflicts: [], charges: [], away: 0, duty: false, earnsOil: 0, annualFull: false,
}) as DayView

/* only leave and medical come in halves in the squadron's vocabulary
   (`codes.ts parseCell`); a course, OD or credit prints bare whatever part of
   the day it takes — its window still counts for manning and clashes */
function notation(code: string, w: Win): string {
  if (!LEAVE.has(code) && !SICK.has(code) && code !== 'ATTB') return code
  const p = portionOf(w)
  return p === 'am' ? `*${code}` : p === 'pm' ? `${code}*` : code
}

/* which record pays for one half: the leave covering more of that half, a tie
   to the earlier start (owner answer D), then the filed absence over a
   request, then the id */
function payerFor(half: Win, cs: Contrib[]): Contrib | null {
  const ranked = cs.filter(c => minutesIn(c.win, half) > 0).sort((x, y) =>
    minutesIn(y.win, half) - minutesIn(x.win, half)
    || x.win[0] - y.win[0]
    || (x.kind === 'absence' ? 0 : 1) - (y.kind === 'absence' ? 0 : 1)
    || (x.id < y.id ? -1 : x.id > y.id ? 1 : 0))
  return ranked[0] ?? null
}

export function dayView(input: readonly Contrib[]): DayView {
  if (!input.length) return EMPTY
  const shown = input.filter(c => !c.spill).slice().sort(compareContrib)
  const conflicts: Array<[Contrib, Contrib]> = []
  for (let i = 0; i < input.length; i++) {
    for (let j = i + 1; j < input.length; j++) {
      const a = input[i]!, b = input[j]!
      if (a.spill && b.spill) continue
      if (forbiddenPair(a, b)) conflicts.push([a, b])
    }
  }
  const main = shown.find(c => c.kind !== 'notice') ?? null
  const notices = shown.some(c => c.kind === 'notice')
  const amber = conflicts.length > 0 || notices
  const more = shown.length - (main ? 1 : 0)

  /* charges: leave absences and undecided leave requests pay; a refused bid
     pays nothing (today's `removesAvailability` rule) */
  const payers = shown.filter(c => LEAVE.has(c.code) &&
    (c.kind === 'absence' || (c.kind === 'request' && c.state !== 'refused')))
  const byId = new Map<string, Charge>()
  for (const half of [AM, PM]) {
    const p = payerFor(half, payers)
    if (!p) continue
    const counter = LEAVE.get(p.code)
    if (!counter) continue
    const prev = byId.get(p.id)
    if (prev) { prev.amount += 0.5; delete prev.half }
    else byId.set(p.id, { counter, amount: 0.5, code: p.code, id: p.id, half: half === AM ? 'am' : 'pm' })
  }

  /* away: the halves any removing record touches. Removing = a filed absence
     other than ATT B, and an undecided request (the worst case the counts
     show — owner, 9 Aug 26). A refused bid and a credit remove nobody (a
     credit is DUTY: at work, off the flying programme). */
  const removing = shown.filter(c =>
    (c.kind === 'absence' && c.code !== 'ATTB' && levelOf(c) < 8) ||
    (c.kind === 'request' && c.state !== 'refused'))
  const amAway = removing.some(c => touchesAM(c.win))
  const pmAway = removing.some(c => touchesPM(c.win))
  const away = (amAway ? 0.5 : 0) + (pmAway ? 0.5 : 0)

  const leaves = shown.filter(c => LEAVE.has(c.code) && (c.kind === 'absence' || (c.kind === 'request' && c.state !== 'refused')))
  const annualFull = leaves.length > 0 && leaves.every(c => isAnnual(c.code)) &&
    leaves.some(c => touchesAM(c.win)) && leaves.some(c => touchesPM(c.win))

  return {
    main,
    all: shown,
    code: main ? notation(main.code, main.win) : null,
    state: !main ? null : main.kind === 'request' ? main.state! : 'approved',
    mark: amber ? '!' : more > 0 ? `+${more}` : '',
    amber,
    conflicts,
    charges: [...byId.values()],
    away,
    /* ON DUTY means the SCHEDULE says he was at work — nothing else (owner,
       20 Sep 26): "it shouldn't by default take him as on duty … count the
       manning based on the schedule … if I add FO or HO on the leave war or
       the OIL tracker it shouldn't be counting that person as working unless
       it's stated in the input or the schedule". So only the app's OWN credit
       stands a man down from flying and counts him in the duty manning. An
       AWARD is a line in his OIL bank and nothing more: it does not take him
       off the programme, and with nothing else on the day he is available to
       work. Weekend/public-holiday work still credits automatically — that
       credit is `auto` and reads exactly as it always did. */
    duty: shown.some(c => c.kind === 'credit' && c.auto),
    earnsOil: shown.reduce((n, c) => n + (c.kind !== 'credit' ? 0 : c.days ?? (c.code === 'FO' ? 1 : c.code === 'HO' ? 0.5 : 0)), 0),
    annualFull,
  }
}
